//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class almanya
    {
        public int id { get; set; }
        public string gelir_gider { get; set; }
        public Nullable<System.DateTime> faturatarihi { get; set; }
        public string faturano { get; set; }
        public string pozisyonno { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string firmaadi { get; set; }
        public Nullable<System.DateTime> odemetarihi { get; set; }
    }
}
