//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DENIZPOZISYONLAR
    {
        public int id { get; set; }
        public string pozisyonno { get; set; }
        public string txtkalkistarihi { get; set; }
        public string txthat { get; set; }
        public string toplamkonteyner { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txttahliyelimani { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtyuklemegemisi { get; set; }
        public string txtyuklemegemisiseferno { get; set; }
        public string txtmblno { get; set; }
        public string txtmbltarihi { get; set; }
        public string txtsube { get; set; }
        public string txtopgrup { get; set; }
        public string txtbeklenenvaristar { get; set; }
        public string txtvaristarihi { get; set; }
        public string toplamhacim { get; set; }
        public string toplambrutagirlik { get; set; }
        public string txtaktarmalimani { get; set; }
        public string txtaktarmagemisi { get; set; }
        public string txtaktarmagemisiseferno { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string txtistipi { get; set; }
        public string txtacilistarihi { get; set; }
        public string txtkapanistarihi { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> Rezerve { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string txtacilistarihilong { get; set; }
        public string pozno { get; set; }
        public Nullable<int> ProjeID { get; set; }
    }
}
