//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bati_serverEntities : DbContext
    {
        public bati_serverEntities()
            : base("name=bati_serverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<almanya> almanya { get; set; }
        public virtual DbSet<FaturaDetay> FaturaDetay { get; set; }
        public virtual DbSet<FaturaMaster> FaturaMaster { get; set; }
        public virtual DbSet<LISTE> LISTE { get; set; }
        public virtual DbSet<SOFTCARI> SOFTCARI { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_AccountDocuments> Tbl_AccountDocuments { get; set; }
        public virtual DbSet<Tbl_Airlines> Tbl_Airlines { get; set; }
        public virtual DbSet<Tbl_Airports> Tbl_Airports { get; set; }
        public virtual DbSet<Tbl_AracEvraklar> Tbl_AracEvraklar { get; set; }
        public virtual DbSet<Tbl_AracKontrolleri> Tbl_AracKontrolleri { get; set; }
        public virtual DbSet<Tbl_Araclar> Tbl_Araclar { get; set; }
        public virtual DbSet<Tbl_AracSoforler> Tbl_AracSoforler { get; set; }
        public virtual DbSet<Tbl_Authority> Tbl_Authority { get; set; }
        public virtual DbSet<Tbl_BABS_Approve> Tbl_BABS_Approve { get; set; }
        public virtual DbSet<Tbl_BABS_Approve_Authority> Tbl_BABS_Approve_Authority { get; set; }
        public virtual DbSet<Tbl_BankDetails> Tbl_BankDetails { get; set; }
        public virtual DbSet<Tbl_Branches> Tbl_Branches { get; set; }
        public virtual DbSet<Tbl_Budget_Locking> Tbl_Budget_Locking { get; set; }
        public virtual DbSet<Tbl_Budget_Shared_Codes> Tbl_Budget_Shared_Codes { get; set; }
        public virtual DbSet<Tbl_BudgetExpectations> Tbl_BudgetExpectations { get; set; }
        public virtual DbSet<Tbl_BudgetExpects> Tbl_BudgetExpects { get; set; }
        public virtual DbSet<Tbl_Calendar> Tbl_Calendar { get; set; }
        public virtual DbSet<Tbl_CalendarEvents> Tbl_CalendarEvents { get; set; }
        public virtual DbSet<Tbl_CalisanToplamlari> Tbl_CalisanToplamlari { get; set; }
        public virtual DbSet<Tbl_CariVadeler> Tbl_CariVadeler { get; set; }
        public virtual DbSet<Tbl_City> Tbl_City { get; set; }
        public virtual DbSet<Tbl_CntrTracking> Tbl_CntrTracking { get; set; }
        public virtual DbSet<Tbl_CntrTracking_Locations> Tbl_CntrTracking_Locations { get; set; }
        public virtual DbSet<Tbl_Contacts> Tbl_Contacts { get; set; }
        public virtual DbSet<Tbl_Container_Codes> Tbl_Container_Codes { get; set; }
        public virtual DbSet<Tbl_ContainerEvents> Tbl_ContainerEvents { get; set; }
        public virtual DbSet<Tbl_Counter_Templates> Tbl_Counter_Templates { get; set; }
        public virtual DbSet<Tbl_Countries> Tbl_Countries { get; set; }
        public virtual DbSet<Tbl_CrmMenu> Tbl_CrmMenu { get; set; }
        public virtual DbSet<Tbl_Customer_Address_Book> Tbl_Customer_Address_Book { get; set; }
        public virtual DbSet<Tbl_Customer_Contacts> Tbl_Customer_Contacts { get; set; }
        public virtual DbSet<Tbl_Customer_Variables> Tbl_Customer_Variables { get; set; }
        public virtual DbSet<Tbl_DamgaPulu> Tbl_DamgaPulu { get; set; }
        public virtual DbSet<Tbl_Degerler> Tbl_Degerler { get; set; }
        public virtual DbSet<Tbl_DemirbasKalemleri> Tbl_DemirbasKalemleri { get; set; }
        public virtual DbSet<Tbl_Demirbaslar> Tbl_Demirbaslar { get; set; }
        public virtual DbSet<Tbl_Denizyolu_Ticari> Tbl_Denizyolu_Ticari { get; set; }
        public virtual DbSet<Tbl_DepoMuhasebeHesaplari> Tbl_DepoMuhasebeHesaplari { get; set; }
        public virtual DbSet<Tbl_DofForms> Tbl_DofForms { get; set; }
        public virtual DbSet<Tbl_DovizKurlari> Tbl_DovizKurlari { get; set; }
        public virtual DbSet<Tbl_EInvoice> Tbl_EInvoice { get; set; }
        public virtual DbSet<Tbl_EInvoiceGB> Tbl_EInvoiceGB { get; set; }
        public virtual DbSet<Tbl_EInvoicePK> Tbl_EInvoicePK { get; set; }
        public virtual DbSet<Tbl_Employee_Hierarchy> Tbl_Employee_Hierarchy { get; set; }
        public virtual DbSet<Tbl_Envanter> Tbl_Envanter { get; set; }
        public virtual DbSet<Tbl_EvrakArsiv> Tbl_EvrakArsiv { get; set; }
        public virtual DbSet<Tbl_EvrakIcerikler> Tbl_EvrakIcerikler { get; set; }
        public virtual DbSet<Tbl_EvrakIstipi> Tbl_EvrakIstipi { get; set; }
        public virtual DbSet<Tbl_Evraklar> Tbl_Evraklar { get; set; }
        public virtual DbSet<Tbl_EvrakSablonIstipi> Tbl_EvrakSablonIstipi { get; set; }
        public virtual DbSet<Tbl_EvrakSablonlari> Tbl_EvrakSablonlari { get; set; }
        public virtual DbSet<Tbl_EvrakSablonTurleri> Tbl_EvrakSablonTurleri { get; set; }
        public virtual DbSet<Tbl_EvrakTurleri> Tbl_EvrakTurleri { get; set; }
        public virtual DbSet<Tbl_FaturaTalimatlari> Tbl_FaturaTalimatlari { get; set; }
        public virtual DbSet<Tbl_Flexi_Seri> Tbl_Flexi_Seri { get; set; }
        public virtual DbSet<Tbl_FreightRequest> Tbl_FreightRequest { get; set; }
        public virtual DbSet<Tbl_FreightRequestResponse> Tbl_FreightRequestResponse { get; set; }
        public virtual DbSet<Tbl_FreightRequestResponseItems> Tbl_FreightRequestResponseItems { get; set; }
        public virtual DbSet<Tbl_GiderKalemleri> Tbl_GiderKalemleri { get; set; }
        public virtual DbSet<Tbl_GoruntulenenEvraklar> Tbl_GoruntulenenEvraklar { get; set; }
        public virtual DbSet<Tbl_GorusmeBilgilendirme> Tbl_GorusmeBilgilendirme { get; set; }
        public virtual DbSet<Tbl_HavaFirmalari> Tbl_HavaFirmalari { get; set; }
        public virtual DbSet<Tbl_HavaKonteyner> Tbl_HavaKonteyner { get; set; }
        public virtual DbSet<Tbl_HavaLoads> Tbl_HavaLoads { get; set; }
        public virtual DbSet<Tbl_HavaPozisyonlar> Tbl_HavaPozisyonlar { get; set; }
        public virtual DbSet<Tbl_HavaRezervasyonlar> Tbl_HavaRezervasyonlar { get; set; }
        public virtual DbSet<Tbl_Havayolu_Seri> Tbl_Havayolu_Seri { get; set; }
        public virtual DbSet<Tbl_HsCodes> Tbl_HsCodes { get; set; }
        public virtual DbSet<Tbl_Infinity_Menu> Tbl_Infinity_Menu { get; set; }
        public virtual DbSet<Tbl_Inform_Company> Tbl_Inform_Company { get; set; }
        public virtual DbSet<Tbl_InlandAgency> Tbl_InlandAgency { get; set; }
        public virtual DbSet<TBL_INTRA_TRACKING> TBL_INTRA_TRACKING { get; set; }
        public virtual DbSet<Tbl_Inttra_Transactions> Tbl_Inttra_Transactions { get; set; }
        public virtual DbSet<Tbl_InttraBC> Tbl_InttraBC { get; set; }
        public virtual DbSet<Tbl_IsAkisMerkezi> Tbl_IsAkisMerkezi { get; set; }
        public virtual DbSet<Tbl_Kalemler> Tbl_Kalemler { get; set; }
        public virtual DbSet<Tbl_KaraKonteyner> Tbl_KaraKonteyner { get; set; }
        public virtual DbSet<Tbl_KaraLoads> Tbl_KaraLoads { get; set; }
        public virtual DbSet<Tbl_KaraPozisyonlar> Tbl_KaraPozisyonlar { get; set; }
        public virtual DbSet<Tbl_KayitliTarifeler> Tbl_KayitliTarifeler { get; set; }
        public virtual DbSet<Tbl_KayitliTeklifKalemleri> Tbl_KayitliTeklifKalemleri { get; set; }
        public virtual DbSet<Tbl_KoliBilgileri> Tbl_KoliBilgileri { get; set; }
        public virtual DbSet<Tbl_Konteyner> Tbl_Konteyner { get; set; }
        public virtual DbSet<Tbl_KullaniciEvraklari> Tbl_KullaniciEvraklari { get; set; }
        public virtual DbSet<Tbl_KullaniciMuhasebeKodlari> Tbl_KullaniciMuhasebeKodlari { get; set; }
        public virtual DbSet<Tbl_KullaniciRaporGruplari> Tbl_KullaniciRaporGruplari { get; set; }
        public virtual DbSet<Tbl_Kunye_Paket> Tbl_Kunye_Paket { get; set; }
        public virtual DbSet<Tbl_Kunye_Prim_Oranlar> Tbl_Kunye_Prim_Oranlar { get; set; }
        public virtual DbSet<Tbl_Kunye_User_Match> Tbl_Kunye_User_Match { get; set; }
        public virtual DbSet<Tbl_Loads> Tbl_Loads { get; set; }
        public virtual DbSet<Tbl_Locations> Tbl_Locations { get; set; }
        public virtual DbSet<Tbl_Logo_Donemler> Tbl_Logo_Donemler { get; set; }
        public virtual DbSet<Tbl_LogoGiderler> Tbl_LogoGiderler { get; set; }
        public virtual DbSet<Tbl_Logs> Tbl_Logs { get; set; }
        public virtual DbSet<Tbl_MailGroups> Tbl_MailGroups { get; set; }
        public virtual DbSet<Tbl_MailSetup> Tbl_MailSetup { get; set; }
        public virtual DbSet<Tbl_MalzemeListesi> Tbl_MalzemeListesi { get; set; }
        public virtual DbSet<Tbl_Masraflar> Tbl_Masraflar { get; set; }
        public virtual DbSet<Tbl_Mawb_Stok> Tbl_Mawb_Stok { get; set; }
        public virtual DbSet<Tbl_MCode_Request> Tbl_MCode_Request { get; set; }
        public virtual DbSet<Tbl_MeetingCustomer> Tbl_MeetingCustomer { get; set; }
        public virtual DbSet<Tbl_Meetings> Tbl_Meetings { get; set; }
        public virtual DbSet<Tbl_MeetingStaff> Tbl_MeetingStaff { get; set; }
        public virtual DbSet<Tbl_Menu> Tbl_Menu { get; set; }
        public virtual DbSet<Tbl_Messenger> Tbl_Messenger { get; set; }
        public virtual DbSet<Tbl_Moduls> Tbl_Moduls { get; set; }
        public virtual DbSet<Tbl_MT_Vessels> Tbl_MT_Vessels { get; set; }
        public virtual DbSet<Tbl_MT_Vessels_Locations> Tbl_MT_Vessels_Locations { get; set; }
        public virtual DbSet<Tbl_MuhasebeSayaclar> Tbl_MuhasebeSayaclar { get; set; }
        public virtual DbSet<Tbl_Notifier> Tbl_Notifier { get; set; }
        public virtual DbSet<Tbl_OdemeTalimatlari> Tbl_OdemeTalimatlari { get; set; }
        public virtual DbSet<Tbl_OffDateForms> Tbl_OffDateForms { get; set; }
        public virtual DbSet<Tbl_OffDates> Tbl_OffDates { get; set; }
        public virtual DbSet<Tbl_OnayListesi> Tbl_OnayListesi { get; set; }
        public virtual DbSet<Tbl_Overseas_Invoice> Tbl_Overseas_Invoice { get; set; }
        public virtual DbSet<Tbl_Package_Types> Tbl_Package_Types { get; set; }
        public virtual DbSet<Tbl_PendingList> Tbl_PendingList { get; set; }
        public virtual DbSet<Tbl_PersonelGorevTanimlari> Tbl_PersonelGorevTanimlari { get; set; }
        public virtual DbSet<Tbl_PortAgency> Tbl_PortAgency { get; set; }
        public virtual DbSet<Tbl_PortAgencyLocations> Tbl_PortAgencyLocations { get; set; }
        public virtual DbSet<Tbl_PortRoutes> Tbl_PortRoutes { get; set; }
        public virtual DbSet<Tbl_PozisyonKalemleri> Tbl_PozisyonKalemleri { get; set; }
        public virtual DbSet<Tbl_Pozisyonlar> Tbl_Pozisyonlar { get; set; }
        public virtual DbSet<Tbl_ProjectFollowList> Tbl_ProjectFollowList { get; set; }
        public virtual DbSet<Tbl_ProjePozisyonlar> Tbl_ProjePozisyonlar { get; set; }
        public virtual DbSet<Tbl_ProjeTasimalari> Tbl_ProjeTasimalari { get; set; }
        public virtual DbSet<Tbl_Purchase_Forms> Tbl_Purchase_Forms { get; set; }
        public virtual DbSet<Tbl_Purchase_Items> Tbl_Purchase_Items { get; set; }
        public virtual DbSet<Tbl_Purchase_Types> Tbl_Purchase_Types { get; set; }
        public virtual DbSet<Tbl_Quote_Cargo_Detail> Tbl_Quote_Cargo_Detail { get; set; }
        public virtual DbSet<Tbl_Quote_Expenses> Tbl_Quote_Expenses { get; set; }
        public virtual DbSet<Tbl_Quotes> Tbl_Quotes { get; set; }
        public virtual DbSet<Tbl_Required_Fields> Tbl_Required_Fields { get; set; }
        public virtual DbSet<Tbl_ResmiTatiller> Tbl_ResmiTatiller { get; set; }
        public virtual DbSet<Tbl_Rezervasyon_Deniz> Tbl_Rezervasyon_Deniz { get; set; }
        public virtual DbSet<Tbl_RezervasyonGecmisi> Tbl_RezervasyonGecmisi { get; set; }
        public virtual DbSet<Tbl_RezervasyonKalemleri> Tbl_RezervasyonKalemleri { get; set; }
        public virtual DbSet<Tbl_RezervasyonKonteyner> Tbl_RezervasyonKonteyner { get; set; }
        public virtual DbSet<Tbl_RezHavaKonteyner> Tbl_RezHavaKonteyner { get; set; }
        public virtual DbSet<Tbl_RezHavaLoads> Tbl_RezHavaLoads { get; set; }
        public virtual DbSet<Tbl_RezHavaPozisyonlar> Tbl_RezHavaPozisyonlar { get; set; }
        public virtual DbSet<Tbl_RezKaraKonteyner> Tbl_RezKaraKonteyner { get; set; }
        public virtual DbSet<Tbl_RezKaraLoads> Tbl_RezKaraLoads { get; set; }
        public virtual DbSet<Tbl_RezKaraPozisyonlar> Tbl_RezKaraPozisyonlar { get; set; }
        public virtual DbSet<Tbl_RezKonteyner> Tbl_RezKonteyner { get; set; }
        public virtual DbSet<Tbl_RezLoads> Tbl_RezLoads { get; set; }
        public virtual DbSet<Tbl_RezPozisyonlar> Tbl_RezPozisyonlar { get; set; }
        public virtual DbSet<Tbl_RezYukeBagliTerimler> Tbl_RezYukeBagliTerimler { get; set; }
        public virtual DbSet<Tbl_SabitDegerler> Tbl_SabitDegerler { get; set; }
        public virtual DbSet<Tbl_Sayaclar> Tbl_Sayaclar { get; set; }
        public virtual DbSet<Tbl_Scheduler> Tbl_Scheduler { get; set; }
        public virtual DbSet<Tbl_Sectors> Tbl_Sectors { get; set; }
        public virtual DbSet<Tbl_SeyahatFormlari> Tbl_SeyahatFormlari { get; set; }
        public virtual DbSet<Tbl_ShellToolbox> Tbl_ShellToolbox { get; set; }
        public virtual DbSet<Tbl_Ships> Tbl_Ships { get; set; }
        public virtual DbSet<Tbl_Spetta_Price> Tbl_Spetta_Price { get; set; }
        public virtual DbSet<Tbl_TankStock> Tbl_TankStock { get; set; }
        public virtual DbSet<Tbl_TarifeKalemleri> Tbl_TarifeKalemleri { get; set; }
        public virtual DbSet<Tbl_TarifeKonteyner> Tbl_TarifeKonteyner { get; set; }
        public virtual DbSet<Tbl_Tarifeler> Tbl_Tarifeler { get; set; }
        public virtual DbSet<Tbl_TarifeParsiyel> Tbl_TarifeParsiyel { get; set; }
        public virtual DbSet<Tbl_Tariffs> Tbl_Tariffs { get; set; }
        public virtual DbSet<Tbl_TaxOffices> Tbl_TaxOffices { get; set; }
        public virtual DbSet<Tbl_TeklifKalemleri> Tbl_TeklifKalemleri { get; set; }
        public virtual DbSet<Tbl_TeklifKonteyner> Tbl_TeklifKonteyner { get; set; }
        public virtual DbSet<Tbl_Teklifler> Tbl_Teklifler { get; set; }
        public virtual DbSet<Tbl_TeklifSartlari> Tbl_TeklifSartlari { get; set; }
        public virtual DbSet<Tbl_Terimler> Tbl_Terimler { get; set; }
        public virtual DbSet<Tbl_TrackingLogs> Tbl_TrackingLogs { get; set; }
        public virtual DbSet<Tbl_Trades> Tbl_Trades { get; set; }
        public virtual DbSet<TBL_TRAXON_CONTACTS> TBL_TRAXON_CONTACTS { get; set; }
        public virtual DbSet<Tbl_Traxon_Documents> Tbl_Traxon_Documents { get; set; }
        public virtual DbSet<Tbl_Traxon_Hbl> Tbl_Traxon_Hbl { get; set; }
        public virtual DbSet<Tbl_Traxon_Hbl_Rows> Tbl_Traxon_Hbl_Rows { get; set; }
        public virtual DbSet<TBL_TRAXON_LIST> TBL_TRAXON_LIST { get; set; }
        public virtual DbSet<Tbl_Traxon_OtherCharges> Tbl_Traxon_OtherCharges { get; set; }
        public virtual DbSet<Tbl_Traxon_OutBox> Tbl_Traxon_OutBox { get; set; }
        public virtual DbSet<Tbl_Traxon_Rows> Tbl_Traxon_Rows { get; set; }
        public virtual DbSet<Tbl_Traxon_SPH_Codes> Tbl_Traxon_SPH_Codes { get; set; }
        public virtual DbSet<Tbl_User_Competences> Tbl_User_Competences { get; set; }
        public virtual DbSet<Tbl_User_Individual_Goals> Tbl_User_Individual_Goals { get; set; }
        public virtual DbSet<Tbl_User_InOut> Tbl_User_InOut { get; set; }
        public virtual DbSet<Tbl_User_Performance> Tbl_User_Performance { get; set; }
        public virtual DbSet<Tbl_User_Performances_MatchTable> Tbl_User_Performances_MatchTable { get; set; }
        public virtual DbSet<Tbl_UserPrinters> Tbl_UserPrinters { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<Tbl_UyariMesajiGonderimleri> Tbl_UyariMesajiGonderimleri { get; set; }
        public virtual DbSet<Tbl_VersiyonBilgileri> Tbl_VersiyonBilgileri { get; set; }
        public virtual DbSet<Tbl_Virman> Tbl_Virman { get; set; }
        public virtual DbSet<Tbl_WebReports> Tbl_WebReports { get; set; }
        public virtual DbSet<Tbl_YonetmeEslestirme> Tbl_YonetmeEslestirme { get; set; }
        public virtual DbSet<Tbl_YukeBagliTerimler> Tbl_YukeBagliTerimler { get; set; }
        public virtual DbSet<Tbl_AgentContacts> Tbl_AgentContacts { get; set; }
        public virtual DbSet<Tbl_AgentNetworks> Tbl_AgentNetworks { get; set; }
        public virtual DbSet<Tbl_Agents> Tbl_Agents { get; set; }
        public virtual DbSet<Tbl_AuthorizeUsers> Tbl_AuthorizeUsers { get; set; }
        public virtual DbSet<Tbl_BulkComm> Tbl_BulkComm { get; set; }
        public virtual DbSet<Tbl_Demuraj_Tarifeleri> Tbl_Demuraj_Tarifeleri { get; set; }
        public virtual DbSet<Tbl_DemurajFiyatlari> Tbl_DemurajFiyatlari { get; set; }
        public virtual DbSet<Tbl_FaturaSayaclar> Tbl_FaturaSayaclar { get; set; }
        public virtual DbSet<Tbl_Firmalar> Tbl_Firmalar { get; set; }
        public virtual DbSet<Tbl_GroupAdmins> Tbl_GroupAdmins { get; set; }
        public virtual DbSet<Tbl_isotank> Tbl_isotank { get; set; }
        public virtual DbSet<Tbl_isotank_history> Tbl_isotank_history { get; set; }
        public virtual DbSet<Tbl_Limanlar> Tbl_Limanlar { get; set; }
        public virtual DbSet<Tbl_LoadingPlaces> Tbl_LoadingPlaces { get; set; }
        public virtual DbSet<Tbl_Menus> Tbl_Menus { get; set; }
        public virtual DbSet<Tbl_Ports> Tbl_Ports { get; set; }
        public virtual DbSet<Tbl_ShippingLines> Tbl_ShippingLines { get; set; }
        public virtual DbSet<Tbl_Subeler> Tbl_Subeler { get; set; }
        public virtual DbSet<Tbl_TankPositions> Tbl_TankPositions { get; set; }
        public virtual DbSet<Tbl_TradeItems> Tbl_TradeItems { get; set; }
        public virtual DbSet<Tbl_UserGroupMatches> Tbl_UserGroupMatches { get; set; }
        public virtual DbSet<Tbl_UserGroupNames> Tbl_UserGroupNames { get; set; }
        public virtual DbSet<Tbl_Vessels> Tbl_Vessels { get; set; }
        public virtual DbSet<DENIZPOZISYONLAR> DENIZPOZISYONLAR { get; set; }
        public virtual DbSet<PAZARLAMAISTATISTIK> PAZARLAMAISTATISTIK { get; set; }
        public virtual DbSet<Tbl_AirportCountries> Tbl_AirportCountries { get; set; }
        public virtual DbSet<Tbl_AirportsWCountry> Tbl_AirportsWCountry { get; set; }
        public virtual DbSet<Tbl_AirportWCountryCode> Tbl_AirportWCountryCode { get; set; }
        public virtual DbSet<TBL_ALLFREIGHT_LOADS> TBL_ALLFREIGHT_LOADS { get; set; }
        public virtual DbSet<TBL_CNTR_LOADS> TBL_CNTR_LOADS { get; set; }
        public virtual DbSet<Tbl_CntrDailyEvents> Tbl_CntrDailyEvents { get; set; }
        public virtual DbSet<Tbl_COMBINED_INVOICES> Tbl_COMBINED_INVOICES { get; set; }
        public virtual DbSet<Tbl_CombinedList> Tbl_CombinedList { get; set; }
        public virtual DbSet<Tbl_CustomerTotalsByMonth> Tbl_CustomerTotalsByMonth { get; set; }
        public virtual DbSet<Tbl_EvrakTaramalari> Tbl_EvrakTaramalari { get; set; }
        public virtual DbSet<Tbl_FaturaPozisyonlar> Tbl_FaturaPozisyonlar { get; set; }
        public virtual DbSet<Tbl_FaturaView> Tbl_FaturaView { get; set; }
        public virtual DbSet<Tbl_FlexiView> Tbl_FlexiView { get; set; }
        public virtual DbSet<Tbl_GemiCikis> Tbl_GemiCikis { get; set; }
        public virtual DbSet<Tbl_GemiVaris> Tbl_GemiVaris { get; set; }
        public virtual DbSet<Tbl_IsoTankStock> Tbl_IsoTankStock { get; set; }
        public virtual DbSet<TBL_LINE_TEU_REPORT> TBL_LINE_TEU_REPORT { get; set; }
        public virtual DbSet<TBL_LOADTRACKING> TBL_LOADTRACKING { get; set; }
        public virtual DbSet<Tbl_LocationView> Tbl_LocationView { get; set; }
        public virtual DbSet<TBL_MAG_AKT_HATA> TBL_MAG_AKT_HATA { get; set; }
        public virtual DbSet<Tbl_Marketing_Report> Tbl_Marketing_Report { get; set; }
        public virtual DbSet<Tbl_MarketingTotalsByMonth> Tbl_MarketingTotalsByMonth { get; set; }
        public virtual DbSet<Tbl_MontlySales> Tbl_MontlySales { get; set; }
        public virtual DbSet<Tbl_MontlySalesByPersonelID> Tbl_MontlySalesByPersonelID { get; set; }
        public virtual DbSet<Tbl_Operations_Report> Tbl_Operations_Report { get; set; }
        public virtual DbSet<Tbl_OperationTotalsByMonth> Tbl_OperationTotalsByMonth { get; set; }
        public virtual DbSet<Tbl_Pivot> Tbl_Pivot { get; set; }
        public virtual DbSet<Tbl_PivotFingers> Tbl_PivotFingers { get; set; }
        public virtual DbSet<TBL_POS_LOADS> TBL_POS_LOADS { get; set; }
        public virtual DbSet<TBL_POZKALEM_FILTRE> TBL_POZKALEM_FILTRE { get; set; }
        public virtual DbSet<Tbl_ProfitByCountry> Tbl_ProfitByCountry { get; set; }
        public virtual DbSet<Tbl_ProfitByCountry_Operations> Tbl_ProfitByCountry_Operations { get; set; }
        public virtual DbSet<Tbl_Proje_All> Tbl_Proje_All { get; set; }
        public virtual DbSet<Tbl_ShellView> Tbl_ShellView { get; set; }
        public virtual DbSet<Tbl_StokAirlineTotals> Tbl_StokAirlineTotals { get; set; }
        public virtual DbSet<Tbl_StokView> Tbl_StokView { get; set; }
        public virtual DbSet<Tbl_TaranmisEvraklar> Tbl_TaranmisEvraklar { get; set; }
        public virtual DbSet<Tbl_TekliflerView> Tbl_TekliflerView { get; set; }
        public virtual DbSet<TBL_TOPCUSTOMERS> TBL_TOPCUSTOMERS { get; set; }
        public virtual DbSet<TBL_TOPLIST> TBL_TOPLIST { get; set; }
        public virtual DbSet<Tbl_TrackingView> Tbl_TrackingView { get; set; }
        public virtual DbSet<TBL_WEB_HBL> TBL_WEB_HBL { get; set; }
        public virtual DbSet<Tbl_WebPivot> Tbl_WebPivot { get; set; }
        public virtual DbSet<Tbl_Weekly_Visits> Tbl_Weekly_Visits { get; set; }
        public virtual DbSet<Tbl_YildizliKalemler> Tbl_YildizliKalemler { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TotalsByShipper> TotalsByShipper { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<Tbl_BlacklistNotes> Tbl_BlacklistNotes { get; set; }
        public virtual DbSet<Tbl_AdresKartlari> Tbl_AdresKartlari { get; set; }
        public virtual DbSet<Tbl_MaturityRequests> Tbl_MaturityRequests { get; set; }
    
        [DbFunction("bati_serverEntities", "fnSplit")]
        public virtual IQueryable<fnSplit_Result> fnSplit(string sInputList, string sDelimiter)
        {
            var sInputListParameter = sInputList != null ?
                new ObjectParameter("sInputList", sInputList) :
                new ObjectParameter("sInputList", typeof(string));
    
            var sDelimiterParameter = sDelimiter != null ?
                new ObjectParameter("sDelimiter", sDelimiter) :
                new ObjectParameter("sDelimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnSplit_Result>("[bati_serverEntities].[fnSplit](@sInputList, @sDelimiter)", sInputListParameter, sDelimiterParameter);
        }
    
        [DbFunction("bati_serverEntities", "GetHierarchy")]
        public virtual IQueryable<GetHierarchy_Result> GetHierarchy(Nullable<int> employeeID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetHierarchy_Result>("[bati_serverEntities].[GetHierarchy](@EmployeeID)", employeeIDParameter);
        }
    
        [DbFunction("bati_serverEntities", "ReplaceBlLoad")]
        public virtual IQueryable<ReplaceBlLoad_Result> ReplaceBlLoad(string bLNo)
        {
            var bLNoParameter = bLNo != null ?
                new ObjectParameter("BLNo", bLNo) :
                new ObjectParameter("BLNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ReplaceBlLoad_Result>("[bati_serverEntities].[ReplaceBlLoad](@BLNo)", bLNoParameter);
        }
    
        public virtual ObjectResult<AdresKartlari_Result> AdresKartlari(string dkod, string dunvan, string dcountry, string dcity, string dbolge)
        {
            var dkodParameter = dkod != null ?
                new ObjectParameter("dkod", dkod) :
                new ObjectParameter("dkod", typeof(string));
    
            var dunvanParameter = dunvan != null ?
                new ObjectParameter("dunvan", dunvan) :
                new ObjectParameter("dunvan", typeof(string));
    
            var dcountryParameter = dcountry != null ?
                new ObjectParameter("dcountry", dcountry) :
                new ObjectParameter("dcountry", typeof(string));
    
            var dcityParameter = dcity != null ?
                new ObjectParameter("dcity", dcity) :
                new ObjectParameter("dcity", typeof(string));
    
            var dbolgeParameter = dbolge != null ?
                new ObjectParameter("dbolge", dbolge) :
                new ObjectParameter("dbolge", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdresKartlari_Result>("AdresKartlari", dkodParameter, dunvanParameter, dcountryParameter, dcityParameter, dbolgeParameter);
        }
    
        public virtual int AdresLogo(Nullable<int> adresID)
        {
            var adresIDParameter = adresID.HasValue ?
                new ObjectParameter("AdresID", adresID) :
                new ObjectParameter("AdresID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdresLogo", adresIDParameter);
        }
    
        public virtual int AdvancedInvoiceSearch(string modulID, string belgeTarih, string belgeTarih2, string islemTarih, string islemTarih2, string belgeTutar, string belgeTutar2, string firmaKodu, string belgeNo, string bimNo, string logoFirmaNo, string logoKurNo, Nullable<int> cariAktarim, Nullable<int> muhasebeAktarim, Nullable<int> sube, Nullable<int> status, Nullable<int> faturaTipi)
        {
            var modulIDParameter = modulID != null ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(string));
    
            var belgeTarihParameter = belgeTarih != null ?
                new ObjectParameter("BelgeTarih", belgeTarih) :
                new ObjectParameter("BelgeTarih", typeof(string));
    
            var belgeTarih2Parameter = belgeTarih2 != null ?
                new ObjectParameter("BelgeTarih2", belgeTarih2) :
                new ObjectParameter("BelgeTarih2", typeof(string));
    
            var islemTarihParameter = islemTarih != null ?
                new ObjectParameter("IslemTarih", islemTarih) :
                new ObjectParameter("IslemTarih", typeof(string));
    
            var islemTarih2Parameter = islemTarih2 != null ?
                new ObjectParameter("IslemTarih2", islemTarih2) :
                new ObjectParameter("IslemTarih2", typeof(string));
    
            var belgeTutarParameter = belgeTutar != null ?
                new ObjectParameter("BelgeTutar", belgeTutar) :
                new ObjectParameter("BelgeTutar", typeof(string));
    
            var belgeTutar2Parameter = belgeTutar2 != null ?
                new ObjectParameter("BelgeTutar2", belgeTutar2) :
                new ObjectParameter("BelgeTutar2", typeof(string));
    
            var firmaKoduParameter = firmaKodu != null ?
                new ObjectParameter("FirmaKodu", firmaKodu) :
                new ObjectParameter("FirmaKodu", typeof(string));
    
            var belgeNoParameter = belgeNo != null ?
                new ObjectParameter("BelgeNo", belgeNo) :
                new ObjectParameter("BelgeNo", typeof(string));
    
            var bimNoParameter = bimNo != null ?
                new ObjectParameter("BimNo", bimNo) :
                new ObjectParameter("BimNo", typeof(string));
    
            var logoFirmaNoParameter = logoFirmaNo != null ?
                new ObjectParameter("LogoFirmaNo", logoFirmaNo) :
                new ObjectParameter("LogoFirmaNo", typeof(string));
    
            var logoKurNoParameter = logoKurNo != null ?
                new ObjectParameter("LogoKurNo", logoKurNo) :
                new ObjectParameter("LogoKurNo", typeof(string));
    
            var cariAktarimParameter = cariAktarim.HasValue ?
                new ObjectParameter("CariAktarim", cariAktarim) :
                new ObjectParameter("CariAktarim", typeof(int));
    
            var muhasebeAktarimParameter = muhasebeAktarim.HasValue ?
                new ObjectParameter("MuhasebeAktarim", muhasebeAktarim) :
                new ObjectParameter("MuhasebeAktarim", typeof(int));
    
            var subeParameter = sube.HasValue ?
                new ObjectParameter("Sube", sube) :
                new ObjectParameter("Sube", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var faturaTipiParameter = faturaTipi.HasValue ?
                new ObjectParameter("FaturaTipi", faturaTipi) :
                new ObjectParameter("FaturaTipi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdvancedInvoiceSearch", modulIDParameter, belgeTarihParameter, belgeTarih2Parameter, islemTarihParameter, islemTarih2Parameter, belgeTutarParameter, belgeTutar2Parameter, firmaKoduParameter, belgeNoParameter, bimNoParameter, logoFirmaNoParameter, logoKurNoParameter, cariAktarimParameter, muhasebeAktarimParameter, subeParameter, statusParameter, faturaTipiParameter);
        }
    
        public virtual ObjectResult<DegerListesi_Result> DegerListesi(string baslik, string deger, string kod, string tur, string deger1, string deger2)
        {
            var baslikParameter = baslik != null ?
                new ObjectParameter("baslik", baslik) :
                new ObjectParameter("baslik", typeof(string));
    
            var degerParameter = deger != null ?
                new ObjectParameter("deger", deger) :
                new ObjectParameter("deger", typeof(string));
    
            var kodParameter = kod != null ?
                new ObjectParameter("kod", kod) :
                new ObjectParameter("kod", typeof(string));
    
            var turParameter = tur != null ?
                new ObjectParameter("tur", tur) :
                new ObjectParameter("tur", typeof(string));
    
            var deger1Parameter = deger1 != null ?
                new ObjectParameter("deger1", deger1) :
                new ObjectParameter("deger1", typeof(string));
    
            var deger2Parameter = deger2 != null ?
                new ObjectParameter("deger2", deger2) :
                new ObjectParameter("deger2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DegerListesi_Result>("DegerListesi", baslikParameter, degerParameter, kodParameter, turParameter, deger1Parameter, deger2Parameter);
        }
    
        public virtual ObjectResult<string> EvrakSayaci(Nullable<int> firmaNo, Nullable<int> firmaSube, Nullable<int> yil, string sutun)
        {
            var firmaNoParameter = firmaNo.HasValue ?
                new ObjectParameter("FirmaNo", firmaNo) :
                new ObjectParameter("FirmaNo", typeof(int));
    
            var firmaSubeParameter = firmaSube.HasValue ?
                new ObjectParameter("FirmaSube", firmaSube) :
                new ObjectParameter("FirmaSube", typeof(int));
    
            var yilParameter = yil.HasValue ?
                new ObjectParameter("Yil", yil) :
                new ObjectParameter("Yil", typeof(int));
    
            var sutunParameter = sutun != null ?
                new ObjectParameter("Sutun", sutun) :
                new ObjectParameter("Sutun", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EvrakSayaci", firmaNoParameter, firmaSubeParameter, yilParameter, sutunParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> GEC_KALAN_PERSONEL(Nullable<System.DateTime> fIRSTDATE, Nullable<System.DateTime> lASTDATE)
        {
            var fIRSTDATEParameter = fIRSTDATE.HasValue ?
                new ObjectParameter("FIRSTDATE", fIRSTDATE) :
                new ObjectParameter("FIRSTDATE", typeof(System.DateTime));
    
            var lASTDATEParameter = lASTDATE.HasValue ?
                new ObjectParameter("LASTDATE", lASTDATE) :
                new ObjectParameter("LASTDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("GEC_KALAN_PERSONEL", fIRSTDATEParameter, lASTDATEParameter);
        }
    
        public virtual int general_select2(string tblname, string key)
        {
            var tblnameParameter = tblname != null ?
                new ObjectParameter("tblname", tblname) :
                new ObjectParameter("tblname", typeof(string));
    
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("general_select2", tblnameParameter, keyParameter);
        }
    
        public virtual int GetUsedOffDates(Nullable<int> userID, string baslangic, string bitis, ObjectParameter totalUsed)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var baslangicParameter = baslangic != null ?
                new ObjectParameter("Baslangic", baslangic) :
                new ObjectParameter("Baslangic", typeof(string));
    
            var bitisParameter = bitis != null ?
                new ObjectParameter("Bitis", bitis) :
                new ObjectParameter("Bitis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetUsedOffDates", userIDParameter, baslangicParameter, bitisParameter, totalUsed);
        }
    
        public virtual ObjectResult<Instant_Invoices_Result> Instant_Invoices(Nullable<int> modulID, Nullable<int> recordID)
        {
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            var recordIDParameter = recordID.HasValue ?
                new ObjectParameter("RecordID", recordID) :
                new ObjectParameter("RecordID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Instant_Invoices_Result>("Instant_Invoices", modulIDParameter, recordIDParameter);
        }
    
        public virtual ObjectResult<KalemListesi_Result> KalemListesi(string kalemadi, string ab, string kdvdurum)
        {
            var kalemadiParameter = kalemadi != null ?
                new ObjectParameter("kalemadi", kalemadi) :
                new ObjectParameter("kalemadi", typeof(string));
    
            var abParameter = ab != null ?
                new ObjectParameter("ab", ab) :
                new ObjectParameter("ab", typeof(string));
    
            var kdvdurumParameter = kdvdurum != null ?
                new ObjectParameter("kdvdurum", kdvdurum) :
                new ObjectParameter("kdvdurum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KalemListesi_Result>("KalemListesi", kalemadiParameter, abParameter, kdvdurumParameter);
        }
    
        public virtual int KarZararGuncelle(Nullable<int> yukID, Nullable<int> modulID)
        {
            var yukIDParameter = yukID.HasValue ?
                new ObjectParameter("YukID", yukID) :
                new ObjectParameter("YukID", typeof(int));
    
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KarZararGuncelle", yukIDParameter, modulIDParameter);
        }
    
        public virtual ObjectResult<LocationsList_Result> LocationsList(string locCode)
        {
            var locCodeParameter = locCode != null ?
                new ObjectParameter("LocCode", locCode) :
                new ObjectParameter("LocCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationsList_Result>("LocationsList", locCodeParameter);
        }
    
        public virtual ObjectResult<MGL_STATUS_Result> MGL_STATUS(Nullable<System.DateTime> fIRSTDATE, Nullable<System.DateTime> lASTDATE)
        {
            var fIRSTDATEParameter = fIRSTDATE.HasValue ?
                new ObjectParameter("FIRSTDATE", fIRSTDATE) :
                new ObjectParameter("FIRSTDATE", typeof(System.DateTime));
    
            var lASTDATEParameter = lASTDATE.HasValue ?
                new ObjectParameter("LASTDATE", lASTDATE) :
                new ObjectParameter("LASTDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MGL_STATUS_Result>("MGL_STATUS", fIRSTDATEParameter, lASTDATEParameter);
        }
    
        public virtual int MGL_TOPACCOUNTS(Nullable<int> modulID, Nullable<int> firmaNo, string gruplamaAdi, string gruplamaDegeri)
        {
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            var firmaNoParameter = firmaNo.HasValue ?
                new ObjectParameter("FirmaNo", firmaNo) :
                new ObjectParameter("FirmaNo", typeof(int));
    
            var gruplamaAdiParameter = gruplamaAdi != null ?
                new ObjectParameter("GruplamaAdi", gruplamaAdi) :
                new ObjectParameter("GruplamaAdi", typeof(string));
    
            var gruplamaDegeriParameter = gruplamaDegeri != null ?
                new ObjectParameter("GruplamaDegeri", gruplamaDegeri) :
                new ObjectParameter("GruplamaDegeri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MGL_TOPACCOUNTS", modulIDParameter, firmaNoParameter, gruplamaAdiParameter, gruplamaDegeriParameter);
        }
    
        public virtual int MGL_TOPACCOUNTS_NG(Nullable<int> modulID, Nullable<int> firmaNo, string gruplamaAdi, string gruplamaDegeri, string start_dt, string end_dt, string compNr, string braNr, string salesType)
        {
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            var firmaNoParameter = firmaNo.HasValue ?
                new ObjectParameter("FirmaNo", firmaNo) :
                new ObjectParameter("FirmaNo", typeof(int));
    
            var gruplamaAdiParameter = gruplamaAdi != null ?
                new ObjectParameter("GruplamaAdi", gruplamaAdi) :
                new ObjectParameter("GruplamaAdi", typeof(string));
    
            var gruplamaDegeriParameter = gruplamaDegeri != null ?
                new ObjectParameter("GruplamaDegeri", gruplamaDegeri) :
                new ObjectParameter("GruplamaDegeri", typeof(string));
    
            var start_dtParameter = start_dt != null ?
                new ObjectParameter("start_dt", start_dt) :
                new ObjectParameter("start_dt", typeof(string));
    
            var end_dtParameter = end_dt != null ?
                new ObjectParameter("end_dt", end_dt) :
                new ObjectParameter("end_dt", typeof(string));
    
            var compNrParameter = compNr != null ?
                new ObjectParameter("CompNr", compNr) :
                new ObjectParameter("CompNr", typeof(string));
    
            var braNrParameter = braNr != null ?
                new ObjectParameter("BraNr", braNr) :
                new ObjectParameter("BraNr", typeof(string));
    
            var salesTypeParameter = salesType != null ?
                new ObjectParameter("SalesType", salesType) :
                new ObjectParameter("SalesType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MGL_TOPACCOUNTS_NG", modulIDParameter, firmaNoParameter, gruplamaAdiParameter, gruplamaDegeriParameter, start_dtParameter, end_dtParameter, compNrParameter, braNrParameter, salesTypeParameter);
        }
    
        public virtual int Mgl_Web_LoadsList(string musteriAdi, string firmaNo, string kalkisTarihi)
        {
            var musteriAdiParameter = musteriAdi != null ?
                new ObjectParameter("MusteriAdi", musteriAdi) :
                new ObjectParameter("MusteriAdi", typeof(string));
    
            var firmaNoParameter = firmaNo != null ?
                new ObjectParameter("FirmaNo", firmaNo) :
                new ObjectParameter("FirmaNo", typeof(string));
    
            var kalkisTarihiParameter = kalkisTarihi != null ?
                new ObjectParameter("KalkisTarihi", kalkisTarihi) :
                new ObjectParameter("KalkisTarihi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Mgl_Web_LoadsList", musteriAdiParameter, firmaNoParameter, kalkisTarihiParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_ExpectedProfiteport_Result> SP_ExpectedProfiteport(string startDate, string endDate)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ExpectedProfiteport_Result>("SP_ExpectedProfiteport", startDateParameter, endDateParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_Txt_Split(string sInputList, string delimiter)
        {
            var sInputListParameter = sInputList != null ?
                new ObjectParameter("sInputList", sInputList) :
                new ObjectParameter("sInputList", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Txt_Split", sInputListParameter, delimiterParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Tbl_KullaniciOzet_Result> Tbl_KullaniciOzet(Nullable<int> userID, string nominasyon, Nullable<System.DateTime> baslangic, Nullable<System.DateTime> bitis)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var nominasyonParameter = nominasyon != null ?
                new ObjectParameter("Nominasyon", nominasyon) :
                new ObjectParameter("Nominasyon", typeof(string));
    
            var baslangicParameter = baslangic.HasValue ?
                new ObjectParameter("baslangic", baslangic) :
                new ObjectParameter("baslangic", typeof(System.DateTime));
    
            var bitisParameter = bitis.HasValue ?
                new ObjectParameter("bitis", bitis) :
                new ObjectParameter("bitis", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_KullaniciOzet_Result>("Tbl_KullaniciOzet", userIDParameter, nominasyonParameter, baslangicParameter, bitisParameter);
        }
    
        public virtual ObjectResult<Tbl_Monthly_Loads_Result> Tbl_Monthly_Loads(Nullable<int> personelID, Nullable<int> yil)
        {
            var personelIDParameter = personelID.HasValue ?
                new ObjectParameter("PersonelID", personelID) :
                new ObjectParameter("PersonelID", typeof(int));
    
            var yilParameter = yil.HasValue ?
                new ObjectParameter("Yil", yil) :
                new ObjectParameter("Yil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Monthly_Loads_Result>("Tbl_Monthly_Loads", personelIDParameter, yilParameter);
        }
    
        public virtual ObjectResult<Tbl_WeeklyOpr_Result> Tbl_WeeklyOpr(Nullable<int> userID, Nullable<System.DateTime> tarih)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_WeeklyOpr_Result>("Tbl_WeeklyOpr", userIDParameter, tarihParameter);
        }
    
        public virtual ObjectResult<TerimListesi_Result> TerimListesi(Nullable<int> yukID)
        {
            var yukIDParameter = yukID.HasValue ?
                new ObjectParameter("YukID", yukID) :
                new ObjectParameter("YukID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TerimListesi_Result>("TerimListesi", yukIDParameter);
        }
    }
}
