//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaMaster
    {
        public int Recordid { get; set; }
        public Nullable<short> LogoFirmaNo { get; set; }
        public Nullable<short> LogoDonemNo { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string SeriNo { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<short> FaturaTipi { get; set; }
        public string CHKodu { get; set; }
        public string BelgeNo { get; set; }
        public string OzelKodu { get; set; }
        public string YetkiKodu { get; set; }
        public string SatisElemaniKodu { get; set; }
        public string OdemePlanKodu { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
        public string Aciklama3 { get; set; }
        public string Aciklama4 { get; set; }
        public Nullable<short> IsYeriNo { get; set; }
        public Nullable<short> BolumNo { get; set; }
        public Nullable<short> AmbarNo { get; set; }
        public Nullable<short> IslemDovizTipi { get; set; }
        public Nullable<double> Kur { get; set; }
        public Nullable<short> StatusRecord { get; set; }
        public Nullable<short> Kaynak { get; set; }
        public string LogoHata { get; set; }
        public Nullable<int> PozisyonID { get; set; }
        public string AciklamaGenel { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaKodu { get; set; }
        public string islemtarihi { get; set; }
        public string txtkur { get; set; }
        public string DovizToplam { get; set; }
        public string TLToplam { get; set; }
        public string TLKdvToplam { get; set; }
        public string PozNo { get; set; }
        public string YukNo { get; set; }
        public string KonteynerListesi { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public string GuncellemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
        public string EklemeTarihi { get; set; }
        public Nullable<int> FaturaDurum { get; set; }
        public string iptalnedeni { get; set; }
        public Nullable<int> Modul { get; set; }
        public Nullable<int> ithihr { get; set; }
        public Nullable<int> logoaktarim { get; set; }
        public string Gemiadi { get; set; }
        public string YuklemeLimani { get; set; }
        public string BosaltmaLimani { get; set; }
        public string KonsimentoNo { get; set; }
        public Nullable<int> YeniFatura { get; set; }
        public string FaturaYolu { get; set; }
        public Nullable<int> FaturaSablonID { get; set; }
        public string AKTARIMHATA { get; set; }
        public Nullable<int> GIZLE { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public Nullable<double> OdemeTutari { get; set; }
        public Nullable<int> MailBilgilendirmeDurum { get; set; }
        public string BilgilendirmeMailAdresleri { get; set; }
        public Nullable<System.DateTime> BilgilendirmeTarihi { get; set; }
        public Nullable<int> Tevkifat { get; set; }
    }
}
