//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaDetay
    {
        public int Recordid { get; set; }
        public int MasterRecordid { get; set; }
        public string HizmetKodu { get; set; }
        public string HizmetAdi { get; set; }
        public Nullable<double> Miktar { get; set; }
        public Nullable<double> BirimFiyat { get; set; }
        public Nullable<double> KDVOrani { get; set; }
        public Nullable<short> DovizTipi { get; set; }
        public Nullable<double> Kur { get; set; }
        public string MasrafMerkeziKodu { get; set; }
        public string MuhasebeHesapKodu { get; set; }
        public string HareketOzelKodu { get; set; }
        public string SatirAciklama { get; set; }
        public string PozisyonNo { get; set; }
        public Nullable<int> Tevkifat { get; set; }
    }
}
