//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTE
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description_TR_ { get; set; }
        public string Description_EN_ { get; set; }
        public string Code2 { get; set; }
    }
}
