//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAZARLAMAISTATISTIK
    {
        public int UserID { get; set; }
        public string Name_Surname { get; set; }
        public Nullable<int> TOPLAMKAYIT { get; set; }
        public Nullable<int> TOPLAMGORUSME { get; set; }
        public Nullable<int> TOPLAMTEKLIF { get; set; }
        public Nullable<int> TOPLAMYUK { get; set; }
    }
}
