//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KaraPozisyonlar
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public string RezervasyonNo { get; set; }
        public Nullable<int> Rezerve { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string pozno { get; set; }
        public string pozisyonno { get; set; }
        public string txtistipi { get; set; }
        public string txtsube { get; set; }
        public string txtopgrup { get; set; }
        public string txtacilistarihi { get; set; }
        public string txtacilistarihilong { get; set; }
        public string txtkapanistarihi { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtyurtdisiacentekod { get; set; }
        public string txtcmrno { get; set; }
        public string txtcmrtarihi { get; set; }
        public string txttasiyicifirma { get; set; }
        public string txttasiyicifirmakod { get; set; }
        public string txtaractipi { get; set; }
        public string txtaractipikod { get; set; }
        public string txtaracdolumtarihi { get; set; }
        public string txtkalkistarihi { get; set; }
        public string txtvaristarihi { get; set; }
        public string txtbeklenenvaristarihi { get; set; }
        public string txtgumrukyeri { get; set; }
        public string txtgumrukyerikod { get; set; }
        public string txtincoterms { get; set; }
        public string txtkalkisyeri { get; set; }
        public string txtkalkisyerikod { get; set; }
        public string txtkalkisyeritarihi { get; set; }
        public string txtaktarmayeri { get; set; }
        public string txtaktarmayerikod { get; set; }
        public string txtaktarmayeritar { get; set; }
        public string txtvarisyeri { get; set; }
        public string txtvarisyerikod { get; set; }
        public string txtvarisyeritarihi { get; set; }
        public string txtcikisulkesi { get; set; }
        public string txtcikisulkesikod { get; set; }
        public string txtaktarmaulkesi { get; set; }
        public string txtaktarmaulkesikod { get; set; }
        public string txtvarisulkesi { get; set; }
        public string txtvarisulkesikod { get; set; }
        public Nullable<int> LinerYukleme { get; set; }
        public Nullable<int> CrossYukleme { get; set; }
        public string cmbincoterms { get; set; }
        public string txtnavluntarifesi { get; set; }
        public Nullable<int> txtnavluntardurum { get; set; }
        public string txtdigertarife { get; set; }
        public Nullable<int> txtdigertarifedurum { get; set; }
        public string toplambrutagirlik { get; set; }
        public string toplamnetagirlik { get; set; }
        public string toplamhacim { get; set; }
        public string toplamkolisayisi { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string KullananKullanici { get; set; }
        public string KullanimBaslangic { get; set; }
        public string KullanimSon { get; set; }
        public Nullable<int> KullanimDurum { get; set; }
        public Nullable<int> KarZararDurum { get; set; }
        public string ZararAciklama { get; set; }
        public string txthat { get; set; }
        public string BrutKarZararTL { get; set; }
        public string BrutKarZarar { get; set; }
        public string BrutKarZararEUR { get; set; }
        public string ToplamKarZararTL { get; set; }
        public string ToplamKarZarar { get; set; }
        public string ToplamKarZararEUR { get; set; }
        public string ToplamGelirlerTL { get; set; }
        public string ToplamGelirler { get; set; }
        public string ToplamGelirlerEUR { get; set; }
        public string FinansalGider { get; set; }
        public string FinansalGiderTL { get; set; }
        public string FinansalGiderEUR { get; set; }
        public string KarCiroOrani { get; set; }
        public string TeuAdeti { get; set; }
        public string TeuBasiKarZarar { get; set; }
        public string Kont20adet { get; set; }
        public string Kont40adet { get; set; }
        public string LclWmCbm { get; set; }
        public string LclBasiKarZarar { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<int> ProjeSira { get; set; }
        public string Personel { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> DenetimDurum { get; set; }
        public string DenetimAciklama { get; set; }
        public string txtekbilgi { get; set; }
    }
}
