//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Subeler
    {
        public int id { get; set; }
        public string sube_kodu { get; set; }
        public string sube_adi { get; set; }
        public string eklemetarihi { get; set; }
        public string eklemesaati { get; set; }
        public string Ekleyen { get; set; }
        public Nullable<int> firmaID { get; set; }
        public string firmaKodu { get; set; }
    }
}
