//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_VersiyonBilgileri
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Tur { get; set; }
        public string Aciklama { get; set; }
    }
}
