//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AgentContacts
    {
        public int id { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string txtnamesurname { get; set; }
        public string txttitle { get; set; }
        public string txtemail { get; set; }
        public string txttel { get; set; }
        public string txttel2 { get; set; }
        public string txtmobile { get; set; }
        public string txtfax { get; set; }
    }
}
