//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ships
    {
        public int id { get; set; }
        public string shipname { get; set; }
        public string Imonumber { get; set; }
        public string GrossTonnage { get; set; }
        public string DWT { get; set; }
        public string typeofship { get; set; }
        public string buildyear { get; set; }
        public string shipflag { get; set; }
        public string shipstatus { get; set; }
        public string MMSI { get; set; }
    }
}
