//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PortAgency
    {
        public int id { get; set; }
        public string FirmaKodu { get; set; }
        public string SubeKodu { get; set; }
        public string UlkeKodu { get; set; }
        public Nullable<int> LimanID { get; set; }
        public string LimanAdi { get; set; }
        public string LimanKodu { get; set; }
        public string AcenteAdi { get; set; }
        public string AcenteKodu { get; set; }
        public string UlkeAdi { get; set; }
        public string BolgeAdi { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public string GuncellemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
        public string EklemeTarihi { get; set; }
        public Nullable<int> PortType { get; set; }
        public Nullable<int> OrderNr { get; set; }
    }
}
