//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OperationTotalsByMonth
    {
        public int ID { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<int> YUKADET { get; set; }
        public Nullable<double> TOPLAMTEU { get; set; }
        public Nullable<double> TOPLAMBRUTAGIRLIK { get; set; }
        public string Personel { get; set; }
        public Nullable<int> PersonelID { get; set; }
    }
}
