//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Counter_Templates
    {
        public int ID { get; set; }
        public string COUNTER_NAME { get; set; }
        public string COUNTER_TEMPLATE { get; set; }
        public Nullable<int> COUNTER_START_INDEX { get; set; }
        public Nullable<int> COUNTER_VISIBLE { get; set; }
    }
}
