//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contacts
    {
        public int id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string txtname { get; set; }
        public string txtsurname { get; set; }
        public string txtbirthday { get; set; }
        public string cmbgender { get; set; }
        public string txttel { get; set; }
        public string txtgsm { get; set; }
        public string txtfaks { get; set; }
        public string txtpemail { get; set; }
        public string txthaddress { get; set; }
        public string txtprofession { get; set; }
        public string txtposition { get; set; }
        public string txtdepartment { get; set; }
        public string txtbtel { get; set; }
        public string txtinternal { get; set; }
        public string txtbgsm { get; set; }
        public string txtbemail { get; set; }
        public string txtbaddress { get; set; }
        public string txtweburl { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> PreAlertGonderimi { get; set; }
        public Nullable<bool> GemiCikisIhbariGonderimi { get; set; }
        public Nullable<bool> GemiVarisIhbariGonderimi { get; set; }
        public Nullable<bool> GelirFaturasiGonderimi { get; set; }
        public Nullable<bool> SoaGonderimi { get; set; }
        public string WebPassword { get; set; }
        public string ResetToken { get; set; }
        public Nullable<System.DateTime> TokenTime { get; set; }
        public Nullable<int> WebStatus { get; set; }
        public Nullable<int> Tech_Agreement { get; set; }
        public Nullable<System.DateTime> Tech_Agreement_Date { get; set; }
    }
}
