//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sayaclar
    {
        public int id { get; set; }
        public Nullable<int> CalismaYili { get; set; }
        public string SirketKodu { get; set; }
        public string Sube { get; set; }
        public Nullable<int> teklif_sayaci { get; set; }
        public Nullable<int> rezervasyon_deniz_ithalat { get; set; }
        public Nullable<int> rezervasyon_deniz_ihracat { get; set; }
        public Nullable<int> rezervasyon_hava_ithalat { get; set; }
        public Nullable<int> rezervasyon_hava_ihracat { get; set; }
        public Nullable<int> rezervasyon_kara_ithalat { get; set; }
        public Nullable<int> rezervasyon_kara_ihracat { get; set; }
        public Nullable<int> rezervasyon_tank_ithalat { get; set; }
        public Nullable<int> rezervasyon_tank_ihracat { get; set; }
        public Nullable<int> pozisyon_denizyolu_ithalat { get; set; }
        public Nullable<int> pozisyon_denizyolu_ihracat { get; set; }
        public Nullable<int> pozisyon_havayolu_ithalat { get; set; }
        public Nullable<int> pozisyon_havayolu_ihracat { get; set; }
        public Nullable<int> pozisyon_karayolu_ithalat { get; set; }
        public Nullable<int> pozisyon_karayolu_ihracat { get; set; }
        public Nullable<int> pozisyon_tank_ithalat { get; set; }
        public Nullable<int> pozisyon_tank_ihracat { get; set; }
        public Nullable<int> pozisyon_ticari { get; set; }
        public Nullable<int> rezervasyon_yuk_denizyolu_ihracat { get; set; }
        public Nullable<int> rezervasyon_yuk_denizyolu_ithalat { get; set; }
        public Nullable<int> rezervasyon_yuk_havayolu_ihracat { get; set; }
        public Nullable<int> rezervasyon_yuk_havayolu_ithalat { get; set; }
        public Nullable<int> rezervasyon_yuk_karayolu_ihracat { get; set; }
        public Nullable<int> rezervasyon_yuk_karayolu_ithalat { get; set; }
        public Nullable<int> yuk_denizyolu_ithalat { get; set; }
        public Nullable<int> yuk_denizyolu_ihracat { get; set; }
        public Nullable<int> yuk_havayolu_ithalat { get; set; }
        public Nullable<int> yuk_havayolu_ihracat { get; set; }
        public Nullable<int> yuk_karayolu_ithalat { get; set; }
        public Nullable<int> yuk_karayolu_ihracat { get; set; }
        public Nullable<int> yuk_tank_ithalat { get; set; }
        public Nullable<int> yuk_tank_ihracat { get; set; }
        public Nullable<int> yuk_ticari { get; set; }
        public Nullable<int> yuk_proje_deniz_ithalat { get; set; }
        public Nullable<int> yuk_proje_deniz_ihracat { get; set; }
        public Nullable<int> yuk_proje_hava_ithalat { get; set; }
        public Nullable<int> yuk_proje_hava_ihracat { get; set; }
        public Nullable<int> yuk_proje_kara_ithalat { get; set; }
        public Nullable<int> yuk_proje_kara_ihracat { get; set; }
        public Nullable<int> fatura_sayaci { get; set; }
        public Nullable<int> evrak_sayaci { get; set; }
        public Nullable<int> muhasebe_sayaci { get; set; }
        public Nullable<int> proje_ithalat { get; set; }
        public Nullable<int> proje_ihracat { get; set; }
        public Nullable<int> inttra_booking { get; set; }
        public Nullable<int> inttra_shipping_instructions { get; set; }
        public Nullable<int> masraf_no { get; set; }
        public Nullable<int> satinalma_no { get; set; }
        public Nullable<int> navlun_talebi_no { get; set; }
    }
}
