//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Teklifler
    {
        public int id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string txtfirmaadi { get; set; }
        public string txtfirmakodu { get; set; }
        public string txtilgilikisi { get; set; }
        public string txtilgilikisiemail { get; set; }
        public string txtilgilikisitelefon { get; set; }
        public string txtgecerliliktarihi { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtyuklemelimanikodu { get; set; }
        public string txtvarislimani { get; set; }
        public string txtvarislimanikodu { get; set; }
        public string txtaktarmalimani { get; set; }
        public string txtaktarmalimanikodu { get; set; }
        public string txtyuklemeyeri { get; set; }
        public string txtsonvarisyeri { get; set; }
        public string txtguncelleyenkullanici { get; set; }
        public string txtguncellemetarihi { get; set; }
        public string txtekleyenkullanici { get; set; }
        public string txteklemetarihi { get; set; }
        public string txtnavlundoviz { get; set; }
        public string txt20hafif { get; set; }
        public string txt20agir { get; set; }
        public string txt40hc { get; set; }
        public string txt40dc { get; set; }
        public string txtlcl { get; set; }
        public string txttransitsure { get; set; }
        public string ithihr { get; set; }
        public string ParsiyelKomple { get; set; }
        public Nullable<int> direktservis { get; set; }
        public string cmbmodul { get; set; }
        public string txtnakliyedoviz { get; set; }
        public string txt20hafifnakliye { get; set; }
        public string txt20agirnakliye { get; set; }
        public string txt40hcnakliye { get; set; }
        public string txt40dcnakliye { get; set; }
        public string txtlclnakliye { get; set; }
        public string txtbaslangictarihi { get; set; }
        public string txtnavlunyuklemeyeri { get; set; }
        public string txtnavlunteslimyeri { get; set; }
        public string txthat { get; set; }
        public string txthatkodu { get; set; }
        public string txtaciklama { get; set; }
    }
}
