//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProjectFollowList
    {
        public int FollowID { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> QuatitionDate { get; set; }
        public string Laycan { get; set; }
        public string Company { get; set; }
        public string CompanyCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ContactPerson { get; set; }
        public string ShipmentFrom { get; set; }
        public string ShipmentTo { get; set; }
        public string Commodity { get; set; }
        public string Quantity { get; set; }
        public string HeaviestUnit { get; set; }
        public string ShipmentVia { get; set; }
        public string PolTerms { get; set; }
        public string PodTerms { get; set; }
        public string PersonInCharge { get; set; }
        public string Status { get; set; }
        public string Quoted { get; set; }
        public string LatestSituation { get; set; }
    }
}
