//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RezLoads
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> ithihr { get; set; }
        public Nullable<int> PozisyonID { get; set; }
        public string PozisyonNo { get; set; }
        public string LoadNo { get; set; }
        public string txtmanifestotarihi { get; set; }
        public string txthbltarihi { get; set; }
        public string txtmbltarihi { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txttahliyelimani { get; set; }
        public string txtnihaimevrit { get; set; }
        public string txtmanifestono { get; set; }
        public string txtgumrukyeri { get; set; }
        public string cmbteslimsekli { get; set; }
        public string txtmaladi { get; set; }
        public string OdemeSekli { get; set; }
        public string txtnominasyon { get; set; }
        public string txtsatistipi { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtyuklemeyeri { get; set; }
        public string txtalici { get; set; }
        public string txtgonderici { get; set; }
        public string txtmaladiyabanci { get; set; }
        public string txtnotify { get; set; }
        public string txtmusteriadi { get; set; }
        public string txthblno { get; set; }
        public string txtmblno { get; set; }
        public string toplambrutagirlik { get; set; }
        public string toplamnetagirlik { get; set; }
        public string toplamhacim { get; set; }
        public Nullable<int> toplamkolisayisi { get; set; }
        public string toplamkonteyner { get; set; }
        public string ilkkonteynerno { get; set; }
        public string txtnavluntarifesi { get; set; }
        public string cknavluntarifesi { get; set; }
        public string txtyurtdisiacentetarfesi { get; set; }
        public string ckyurtdisiacentetarifesi { get; set; }
        public string txtlimantarifesi { get; set; }
        public string cklimantarifesi { get; set; }
        public string txticnakliyetarifesi { get; set; }
        public string ckicnakliyetarifesi { get; set; }
        public string txtdemurajtarifesi { get; set; }
        public string ckdemurajtarifesi { get; set; }
        public string txtmusteriadikod { get; set; }
        public string txtgondericikod { get; set; }
        public string txtalicikod { get; set; }
        public string txtnotifykod { get; set; }
        public string txtyurtdisiacentekod { get; set; }
        public string txtyuklemeyerikod { get; set; }
        public string txtyuklemelimanikod { get; set; }
        public string txttahliyelimanikod { get; set; }
        public string txtnihaimevritkod { get; set; }
        public string txtgumrukyerikod { get; set; }
        public string txtgumrukambarikod { get; set; }
        public string txtgumrukambari { get; set; }
        public string ekleyenkullanici { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncellemetarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string markabilgisi { get; set; }
        public string maltanimi { get; set; }
        public string txtmanifestodetay { get; set; }
        public Nullable<int> txtdemalistarifeid { get; set; }
        public Nullable<int> txtdemsatistarifeid { get; set; }
        public string txtdemalistarifeadi { get; set; }
        public string txtdemsatistarifeadi { get; set; }
        public string BrutKarZararTL { get; set; }
        public string BrutKarZarar { get; set; }
        public string BrutKarZararEUR { get; set; }
        public string ToplamKarZararTL { get; set; }
        public string ToplamKarZarar { get; set; }
        public string ToplamKarZararEUR { get; set; }
        public string FinansalGiderTL { get; set; }
        public string FinansalGider { get; set; }
        public string FinansalGiderEUR { get; set; }
        public string ToplamGelirlerTL { get; set; }
        public string ToplamGelirler { get; set; }
        public string ToplamGelirlerEUR { get; set; }
        public string FinansGiderTL { get; set; }
        public string FinansGider { get; set; }
        public string FinansGiderEUR { get; set; }
        public string KdvGiderTL { get; set; }
        public string KdvGider { get; set; }
        public string KdvGiderEUR { get; set; }
        public string ToplamGiderlerTL { get; set; }
        public string ToplamGiderler { get; set; }
        public string ToplamGiderlerEUR { get; set; }
        public string KarCiroOrani { get; set; }
        public string TeuAdeti { get; set; }
        public string TeuBasiKarZarar { get; set; }
        public string Kont20adet { get; set; }
        public string Kont40adet { get; set; }
        public string LclWmCbm { get; set; }
        public string LclBasiKarZarar { get; set; }
        public Nullable<int> OldRezID { get; set; }
        public string txtyuklemeyeripk { get; set; }
        public string txtsonteslimyeripk { get; set; }
        public string txtflexitankno { get; set; }
    }
}
