//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OffDates
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> HalfDay { get; set; }
        public string Total { get; set; }
        public string paidorfree { get; set; }
        public Nullable<int> FormID { get; set; }
    }
}
