//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TRAXON_CONTACTS
    {
        public int ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string PREFIX { get; set; }
        public string CODE2 { get; set; }
        public string AIRLINE_NAME { get; set; }
        public string TRAXON_ADDRESS { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
