//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AracSoforler
    {
        public int ID { get; set; }
        public string Firma { get; set; }
        public string SoforAdSoyad { get; set; }
        public string TcKimlikNo { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string GsmNo { get; set; }
        public string EhliyetSinifi { get; set; }
        public string EhliyetNo { get; set; }
        public Nullable<System.DateTime> EhliyetAlisTarihi { get; set; }
        public Nullable<System.DateTime> SGK_Tarihi { get; set; }
        public Nullable<System.DateTime> Sabika_Kaydi { get; set; }
        public string AdrNo { get; set; }
        public Nullable<System.DateTime> AdrTarihi { get; set; }
        public string SrcNo { get; set; }
        public Nullable<System.DateTime> SrcAlisTarihi { get; set; }
        public Nullable<System.DateTime> YolGuzergahEgitimTarihi { get; set; }
        public Nullable<System.DateTime> DefansifSurusEgitimTarihi { get; set; }
        public Nullable<System.DateTime> ShellAracStandartEgitimTarihi { get; set; }
        public Nullable<System.DateTime> BatiEgitimTarihi { get; set; }
        public Nullable<System.DateTime> CepTelefonKullanimEgitimTarihi { get; set; }
        public Nullable<System.DateTime> Uykusuzluk_Alkol_IlacKullanimEgitimTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
    }
}
