//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KullaniciRaporGruplari
    {
        public int id { get; set; }
        public string RaporAdi { get; set; }
        public string RaporTuru { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Dosya { get; set; }
        public string Text { get; set; }
        public Nullable<int> Modul { get; set; }
        public string EklenmeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
    }
}
