//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Calendar
    {
        public int id { get; set; }
        public string subject { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string label { get; set; }
        public string status { get; set; }
        public string resource { get; set; }
        public string alldayevent { get; set; }
        public string reminder { get; set; }
        public string note { get; set; }
    }
}
