//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CntrDailyEvents
    {
        public long RowNo { get; set; }
        public Nullable<int> id { get; set; }
        public string PozisyonNo { get; set; }
        public string MBL_No { get; set; }
        public string Hat { get; set; }
        public string HatKodu { get; set; }
        public string MBL_Tarihi { get; set; }
        public Nullable<System.DateTime> LastRequestDate { get; set; }
        public string txtsube { get; set; }
        public string txtistipi { get; set; }
    }
}
