//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CombinedList
    {
        public int PozID { get; set; }
        public int YukID { get; set; }
        public string MODUL { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string pozisyonno { get; set; }
        public string txtmblno { get; set; }
        public string txthblno { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txttahliyelimani { get; set; }
        public string txtmusteriadi { get; set; }
        public string txtalici { get; set; }
        public string txtgonderici { get; set; }
        public string KonteynerList { get; set; }
        public string Personel { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string txtnominasyon { get; set; }
    }
}
