//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customer_Contacts
    {
        public int ID { get; set; }
        public Nullable<int> RELATED_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string NAME_SURNAME { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string TITLE { get; set; }
    }
}
