//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Demirbaslar
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public string Sube { get; set; }
        public string FaturaTarihi { get; set; }
        public Nullable<System.DateTime> FaturaTarih { get; set; }
        public string FaturaNo { get; set; }
        public string FaturaFirma { get; set; }
        public string Kodu { get; set; }
        public string Aciklamasi { get; set; }
        public string Teslimalan { get; set; }
        public string Talepeden { get; set; }
        public string faturatutari { get; set; }
        public string doviz { get; set; }
        public string EkleyenKullanici { get; set; }
        public string EklemeTarihi { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public string GuncellemeTarihi { get; set; }
        public byte[] BinaryDosya { get; set; }
        public string BinaryDosyaExt { get; set; }
        public string DosyaAdi { get; set; }
    }
}
