//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Performance
    {
        public int ID { get; set; }
        public string Header { get; set; }
        public Nullable<bool> IsTemplate { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Updater { get; set; }
        public string Explanation1 { get; set; }
        public string Explanation2 { get; set; }
        public string Achievement_Score { get; set; }
    }
}
