//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EvrakTaramalari
    {
        public Nullable<int> Numara { get; set; }
        public string pozisyonno { get; set; }
        public int PozDurum { get; set; }
        public string acilistarihi { get; set; }
        public string txtistipi { get; set; }
        public string txtsube { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string FirmaNo { get; set; }
        public string POZYUK { get; set; }
        public string EvrakTuru { get; set; }
        public string YUKNO { get; set; }
        public int ZORUNLU { get; set; }
    }
}
