//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DofForms
    {
        public int Dof_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TypeOfActivity { get; set; }
        public Nullable<System.DateTime> Impropriety_Date { get; set; }
        public string Impropriety_Place { get; set; }
        public string Impropriety_Departman { get; set; }
        public string Responsible_Staff { get; set; }
        public string Subject { get; set; }
        public string Definition { get; set; }
        public string PreventiveAction { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ResultAndExplanation { get; set; }
        public string PostUser { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
