//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CntrTracking_Locations
    {
        public int LocID { get; set; }
        public Nullable<int> TrackID { get; set; }
        public string BLNo { get; set; }
        public string CNTRNo { get; set; }
        public string Location { get; set; }
        public string LocCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Actual { get; set; }
    }
}
