//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_YildizliKalemler
    {
        public int id { get; set; }
        public string KalemAdi { get; set; }
        public string KalemFirma { get; set; }
        public Nullable<int> SUBE { get; set; }
        public string FirmaNo { get; set; }
        public string PozisyonNo { get; set; }
        public string YukNo { get; set; }
        public string ISTIPI { get; set; }
        public string MODUL { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Durum { get; set; }
        public Nullable<int> AB { get; set; }
        public string orjinaltutar { get; set; }
        public string Orjdoviz { get; set; }
        public string DovizKodu { get; set; }
        public string KalkisTarihi { get; set; }
        public string VarisTarihi { get; set; }
        public string ILGILIKISI { get; set; }
        public Nullable<int> PROJEID { get; set; }
    }
}
