//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MT_Vessels
    {
        public int ID { get; set; }
        public Nullable<int> SHIP_ID { get; set; }
        public Nullable<int> MMSI { get; set; }
        public Nullable<int> IMO { get; set; }
        public string SHIPNAME { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    }
}
