//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DamgaPulu
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> SIRKETNO { get; set; }
        public Nullable<int> SUBE { get; set; }
        public Nullable<int> NO { get; set; }
        public string TUR { get; set; }
        public string FIRMA { get; set; }
        public string FIRMAKODU { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public Nullable<double> MATRAH { get; set; }
        public string BLNO { get; set; }
        public string POZISYONNO { get; set; }
        public string REZERVASYONNO { get; set; }
        public Nullable<int> MODUL { get; set; }
        public Nullable<int> POZID { get; set; }
        public Nullable<int> YUKID { get; set; }
        public string TALEP_EDEN { get; set; }
        public Nullable<System.DateTime> TALEP_TARIHI { get; set; }
        public string ONAYLAYAN { get; set; }
        public Nullable<System.DateTime> ONAY_TARIHI { get; set; }
    }
}
