//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Locations
    {
        public int ID { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public string OperationGroup { get; set; }
        public Nullable<int> OperationGroupCode { get; set; }
        public string LongCode { get; set; }
        public string Location { get; set; }
        public string QueryName { get; set; }
        public string Name { get; set; }
        public string NameWoDiacritics { get; set; }
        public string Subdivision { get; set; }
        public string SubdivisionName { get; set; }
        public string Status { get; set; }
        public string StatusName { get; set; }
        public string FunctionCode { get; set; }
        public string Date { get; set; }
        public string IATA { get; set; }
        public string Coordinates { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AgencyConnection { get; set; }
    }
}
