//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_GoruntulenenEvraklar
    {
        public int id { get; set; }
        public string Evrak_Adi { get; set; }
        public string Evrak_Tarihi { get; set; }
        public string Evrak_No { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaKodu { get; set; }
        public string Ilgisine { get; set; }
        public string Bilgisine { get; set; }
        public string ReferansNo { get; set; }
        public string FaxNo { get; set; }
        public string Kimden { get; set; }
        public string Dosya { get; set; }
        public string PozNo { get; set; }
        public Nullable<int> PozYuk { get; set; }
        public string GuncellemeTarihi { get; set; }
        public Nullable<int> PYID { get; set; }
        public Nullable<int> Modul { get; set; }
        public string BeklenenDegerler { get; set; }
    }
}
