//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_POZKALEM_FILTRE
    {
        public string KalemAdiEN { get; set; }
        public string KalemAdi { get; set; }
        public Nullable<int> AB { get; set; }
        public string Sube { get; set; }
        public string DovizKodu { get; set; }
        public string Firmaadi { get; set; }
        public Nullable<int> FirmaKodu { get; set; }
        public string Belgeno { get; set; }
        public string BelgeTarihi { get; set; }
        public Nullable<double> orjinaltutar { get; set; }
        public Nullable<double> Aratltutari { get; set; }
        public Nullable<double> Kdvtltutari { get; set; }
        public Nullable<double> kdvdahiltutar { get; set; }
        public string kdvhesapno { get; set; }
        public string kdvsizhesapno { get; set; }
        public string yurtdisihesapno { get; set; }
        public int KalemID { get; set; }
    }
}
