//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kunye_Prim_Oranlar
    {
        public int ID { get; set; }
        public Nullable<int> PACK_TYPE { get; set; }
        public string PERF_NOTE { get; set; }
        public Nullable<double> MIN_AMOUNT { get; set; }
        public Nullable<double> MAX_AMOUNT { get; set; }
        public Nullable<double> RATE { get; set; }
    
        public virtual Tbl_Kunye_Paket Tbl_Kunye_Paket { get; set; }
    }
}
