//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Agents
    {
        public int id { get; set; }
        public string Country { get; set; }
        public string Company { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Person { get; set; }
        public string Title { get; set; }
        public string Mail { get; set; }
        public string Web { get; set; }
        public string Ports { get; set; }
        public string Messenger { get; set; }
        public string notes { get; set; }
        public Nullable<bool> ckair { get; set; }
        public Nullable<bool> cksea { get; set; }
        public Nullable<bool> ckland { get; set; }
        public Nullable<bool> cktank { get; set; }
        public Nullable<bool> ckproject { get; set; }
        public Nullable<bool> ckother { get; set; }
        public string networks { get; set; }
    }
}
