//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_StokAirlineTotals
    {
        public int ROWID { get; set; }
        public string FirmaKodu { get; set; }
        public string FirmaAdi { get; set; }
        public Nullable<int> kalan { get; set; }
        public Nullable<int> toplam { get; set; }
    }
}
