//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AccountDocuments
    {
        public int DocumentID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string DocName { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocNr { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string Creator { get; set; }
    }
}
