//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BulkComm
    {
        public int id { get; set; }
        public string txtbcomm { get; set; }
        public string txtunno { get; set; }
        public string txtclass { get; set; }
        public string txtfp { get; set; }
        public string txtpg { get; set; }
        public string ckhazardous { get; set; }
    }
}
