//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Purchase_Forms
    {
        public int ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> PURCHASE_TYPE { get; set; }
        public string REQUEST_NR { get; set; }
        public Nullable<int> FORM_STATUS { get; set; }
        public Nullable<int> REQUESTOR { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
        public Nullable<int> APPROVER { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
        public Nullable<int> BUDGET_APPROVER { get; set; }
        public Nullable<System.DateTime> BUDGET_APPROVER_DATE { get; set; }
    }
}
