//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EInvoice
    {
        public int id { get; set; }
        public string Identifier { get; set; }
        public string Alias { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string FirstCreationTime { get; set; }
        public string AliasCreationTime { get; set; }
        public string RegisterTime { get; set; }
    }
}
