//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALLFREIGHT_LOADS
    {
        public string MODUL { get; set; }
        public int id { get; set; }
        public string toplamkonteyner { get; set; }
        public string txtkonteynerno { get; set; }
        public string txtsiparisno { get; set; }
        public string txtgonderici { get; set; }
        public string txtalici { get; set; }
        public string txtmusteriadi { get; set; }
        public string txtnotify { get; set; }
        public string FirmaNo { get; set; }
        public string txtistipi { get; set; }
        public string txthblno { get; set; }
        public string txtkonteynerdolumtar { get; set; }
        public string txthat { get; set; }
        public string txtyuklemegemisi { get; set; }
        public string txtyuklemegemisiseferno { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtkalkistarihi { get; set; }
        public string txtvaristarihi { get; set; }
        public string txttahliyelimani { get; set; }
        public string txtaktarmalimani { get; set; }
        public string txtaktarmalimanitar { get; set; }
        public string txtmaladiyabanci { get; set; }
        public string txtyukdurum { get; set; }
        public string txtordinoteslimtarihi { get; set; }
        public string pozisyonno { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string toplambrutagirlik { get; set; }
        public string txtbrutagirlik { get; set; }
        public string txtsube { get; set; }
        public string txtacilistarihilong { get; set; }
        public string txtbeklenenvaristar { get; set; }
        public string cmbkonteynerboyu { get; set; }
        public string cmbkonteynertipi { get; set; }
        public string txthacim { get; set; }
        public Nullable<int> LinerYukleme { get; set; }
        public string txtmblno { get; set; }
        public string txtmbltarihi { get; set; }
        public string txtaractipi { get; set; }
        public Nullable<int> txtkolisayisi { get; set; }
        public string cmbpaketseklien { get; set; }
        public string txtaracdolumtarihi { get; set; }
        public string txttasiyicifirma { get; set; }
        public string ilkyuklemeyeri { get; set; }
        public string sonteslimyeri { get; set; }
        public string txtaciklama1 { get; set; }
        public string txtaciklama2 { get; set; }
        public string txtaciklama3 { get; set; }
        public string txtaciklama4 { get; set; }
        public string txtaciklama5 { get; set; }
        public string txtaciklama6 { get; set; }
        public string txtaciklama7 { get; set; }
        public string YuklemeLimanKodu { get; set; }
        public string TahliyeLimanKodu { get; set; }
        public string AktarmaLimanKodu { get; set; }
        public Nullable<int> PozisyonDurum { get; set; }
        public Nullable<int> KonteynerID { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string txtaracyuklemeyeri { get; set; }
        public string txtaracyuklemetarihi { get; set; }
        public string txtaracbosaltmayeri { get; set; }
        public string txtaracbosaltmatarihi { get; set; }
        public string sonteslimtarihi { get; set; }
        public string txtaktarmagemisi { get; set; }
        public Nullable<short> YildizSayisi { get; set; }
        public Nullable<short> YildizSayisi1 { get; set; }
        public Nullable<short> YildizSayisi2 { get; set; }
        public string Yorum { get; set; }
    }
}
