//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Havayolu_Seri
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> HavayoluID { get; set; }
        public Nullable<int> SubeNo { get; set; }
        public string AwbNO { get; set; }
        public string AlisTarihi { get; set; }
        public Nullable<int> AwbSayisi { get; set; }
        public string CikisLimani { get; set; }
        public string CikisLimaniKodu { get; set; }
        public string Baslangicno { get; set; }
        public string Bitisno { get; set; }
        public Nullable<int> RezervasyonID { get; set; }
        public string Durum { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
    }
}
