//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WEB_HBL
    {
        public string pozisyonno1 { get; set; }
        public string txthblno { get; set; }
        public string txthbltarihi { get; set; }
        public string txtgonderici { get; set; }
        public string txtalici { get; set; }
        public string EvrakNo { get; set; }
        public string EvrakTarihi { get; set; }
        public string DosyaAdi { get; set; }
        public string Dosya { get; set; }
        public string Evrak_Adi { get; set; }
        public string EvrakTuru { get; set; }
        public string txtsube { get; set; }
        public string txtistipi { get; set; }
        public Nullable<int> ithihr1 { get; set; }
        public Nullable<int> pozisyonid { get; set; }
        public string FirmaKodu { get; set; }
        public Nullable<int> IHRID { get; set; }
        public Nullable<int> ITHID { get; set; }
        public Nullable<int> LinerBL { get; set; }
        public Nullable<int> CrossBL { get; set; }
    }
}
