//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OffDateForms
    {
        public int FormID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> DayCount { get; set; }
        public Nullable<double> UncutCount { get; set; }
        public string FormType { get; set; }
        public string ExcuseType { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Staff { get; set; }
        public Nullable<double> TotalOffDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
