//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Traxon_Hbl_Rows
    {
        public int ID { get; set; }
        public Nullable<int> DOCID { get; set; }
        public Nullable<int> TOTAL_PIECES { get; set; }
        public Nullable<double> GROSS_WEIGHT { get; set; }
        public string KG_LB { get; set; }
        public string RATE_CLASS { get; set; }
        public string COMMODITY_ITEM_NO { get; set; }
        public Nullable<double> CHARGEABLE_WEIGHT { get; set; }
        public Nullable<double> RATE_CHARGE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string NATURE_QUANTITY_CARGO { get; set; }
        public string CARGO_DESC { get; set; }
        public string HS_CODE_LIST { get; set; }
    }
}
