//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BudgetExpectations
    {
        public int ID { get; set; }
        public Nullable<int> FIRMA { get; set; }
        public int YIL { get; set; }
        public int AY { get; set; }
        public int SUBE { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public string GIDERKODU { get; set; }
        public Nullable<double> CIRO_HEDEF { get; set; }
        public Nullable<double> BRUTKAR_HEDEF { get; set; }
        public Nullable<double> TEU_HEDEF { get; set; }
        public Nullable<double> AGIRLIK_HEDEF { get; set; }
        public Nullable<int> YUKADET_HEDEF { get; set; }
        public Nullable<int> ZIYARET_HEDEF { get; set; }
        public Nullable<double> GIDERKODU_HEDEF { get; set; }
        public string EKLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
