//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TOPLIST
    {
        public string MODUL { get; set; }
        public string CALISMAYILI { get; set; }
        public string AYLAR { get; set; }
        public string SUBE { get; set; }
        public string FirmaNo { get; set; }
        public string FIRMA { get; set; }
        public string ULKE { get; set; }
        public string SEHIR { get; set; }
        public string FIRMATURU { get; set; }
        public string VADETURU { get; set; }
        public string SATISTIPI { get; set; }
        public string NOMINASYON { get; set; }
        public string VADEGUNU { get; set; }
        public string NETWORK { get; set; }
        public int YUKADET { get; set; }
        public Nullable<double> TOPLAMTEU { get; set; }
        public Nullable<double> TOPLAMGELIRLER { get; set; }
        public Nullable<double> KARZARAR { get; set; }
    }
}
