//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TaranmisEvraklar
    {
        public string FirmaNo { get; set; }
        public string PozSube { get; set; }
        public int id { get; set; }
        public string EvrakTuru { get; set; }
        public string EvrakNo { get; set; }
        public string PozisyonNo { get; set; }
        public string PozNo { get; set; }
        public string YukNo { get; set; }
        public string DosyaAdi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string KonteynerNo { get; set; }
        public string EklemeTarihi { get; set; }
        public Nullable<int> Modul { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaKodu { get; set; }
        public string Expr1 { get; set; }
    }
}
