//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProjeTasimalari
    {
        public int id { get; set; }
        public Nullable<int> Tasima { get; set; }
        public string pozisyonno { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<int> PozID { get; set; }
        public Nullable<int> ithihr { get; set; }
        public Nullable<int> ProjeSira { get; set; }
        public Nullable<int> Durum { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtyuklemelimanitar { get; set; }
        public string txttahliyelimani { get; set; }
        public string txttahliyelimanitarihi { get; set; }
        public Nullable<int> toplamkolisayisi { get; set; }
        public string toplamhacim { get; set; }
        public string toplambrutagirlik { get; set; }
        public string toplamnetagirlik { get; set; }
        public string toplamkonteyner { get; set; }
    }
}
