//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IsAkisMerkezi
    {
        public int id { get; set; }
        public Nullable<int> Sirano { get; set; }
        public string BildirenKisi { get; set; }
        public string Tarih { get; set; }
        public string Konu { get; set; }
        public string Aciklama { get; set; }
        public string Durum { get; set; }
        public string Modul { get; set; }
        public string Sirket { get; set; }
        public string Bolum { get; set; }
        public string MaddeTipi { get; set; }
        public string Yetkili { get; set; }
        public Nullable<int> Okundu { get; set; }
        public string KapamaTarihi { get; set; }
        public string IseBaslamaTarihi { get; set; }
    }
}
