//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LogoGiderler
    {
        public int ID { get; set; }
        public Nullable<int> SIRKET { get; set; }
        public Nullable<int> YIL { get; set; }
        public string PROJEKODU { get; set; }
        public string GRUPKODU { get; set; }
        public string MUHKODU { get; set; }
        public string MUHADI { get; set; }
        public Nullable<double> OCAK { get; set; }
        public Nullable<double> SUBAT { get; set; }
        public Nullable<double> MART { get; set; }
        public Nullable<double> NISAN { get; set; }
        public Nullable<double> MAYIS { get; set; }
        public Nullable<double> HAZIRAN { get; set; }
        public Nullable<double> TEMMUZ { get; set; }
        public Nullable<double> AGUSTOS { get; set; }
        public Nullable<double> EYLUL { get; set; }
        public Nullable<double> EKIM { get; set; }
        public Nullable<double> KASIM { get; set; }
        public Nullable<double> ARALIK { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
