//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kunye_Paket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kunye_Paket()
        {
            this.Tbl_Kunye_Prim_Oranlar = new HashSet<Tbl_Kunye_Prim_Oranlar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> YIL { get; set; }
        public string PAKET_ADI { get; set; }
        public Nullable<int> PAKET_TURU { get; set; }
        public Nullable<double> FINANSAL_DOSYA_KARI_USD { get; set; }
        public Nullable<int> FINANSAL_DOSYA_KARI_USD_ETKI { get; set; }
        public Nullable<double> CIRO_USD { get; set; }
        public Nullable<int> CIRO_USD_ETKI { get; set; }
        public Nullable<double> CIRO_DOSYA_KARI_USD_ORANI { get; set; }
        public Nullable<int> CIRO_DOSYA_KARI_USD_ORANI_ETKI { get; set; }
        public Nullable<int> VERILEN_TEKLIF_ADEDI { get; set; }
        public Nullable<int> VERILEN_TEKLIF_ADEDI_ETKI { get; set; }
        public Nullable<int> ONAYLANAN_TEKLIF_ADEDI { get; set; }
        public Nullable<int> ONAYLANAN_TEKLIF_ADEDI_ETKI { get; set; }
        public Nullable<double> TEKLIF_ONAYLANAN_ORANI { get; set; }
        public Nullable<int> TEKLIF_ONAYLANAN_ORANI_ETKI { get; set; }
        public Nullable<int> ZIYARET_ADET { get; set; }
        public Nullable<int> ZIYARET_ADET_ETKI { get; set; }
        public Nullable<int> GORUSME_NOT_ADET { get; set; }
        public Nullable<int> GORUSME_NOT_ADET_ETKI { get; set; }
        public Nullable<int> DENIZYOLU_YUK_ADET { get; set; }
        public Nullable<int> DENIZYOLU_YUK_ADET_ETKI { get; set; }
        public Nullable<int> TEU_ADET { get; set; }
        public Nullable<int> TEU_ADET_ETKI { get; set; }
        public Nullable<int> CNTR_ADET { get; set; }
        public Nullable<int> CNTR_ADET_ETKI { get; set; }
        public Nullable<int> HAVAYOLU_YUK_ADET { get; set; }
        public Nullable<int> HAVAYOLU_YUK_ADET_ETKI { get; set; }
        public Nullable<double> HAVAYOLU_CW_KG { get; set; }
        public Nullable<int> HAVAYOLU_CW_KG_ETKI { get; set; }
        public Nullable<int> KARAYOLU_YUK_ADET { get; set; }
        public Nullable<int> KARAYOLU_YUK_ADET_ETKI { get; set; }
        public Nullable<int> TOPLAM_DOSYA_ADET { get; set; }
        public Nullable<int> TOPLAM_DOSYA_ADET_ETKI { get; set; }
        public Nullable<int> KAPALI_DOSYA_ADET { get; set; }
        public Nullable<int> KAPALI_DOSYA_ADET_ETKI { get; set; }
        public Nullable<int> ACIK_DOSYA_ADET { get; set; }
        public Nullable<int> ACIK_DOSYA_ADET_ETKI { get; set; }
        public Nullable<int> KPI_DENETIM_PUANI { get; set; }
        public Nullable<int> KPI_DENETIM_PUANI_ETKI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kunye_Prim_Oranlar> Tbl_Kunye_Prim_Oranlar { get; set; }
    }
}
