//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PivotFingers
    {
        public int ID { get; set; }
        public string NameSurname { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> Giris { get; set; }
        public Nullable<System.DateTime> Cikis { get; set; }
        public string SubeKodu { get; set; }
        public string GIRISDURUM { get; set; }
        public string CIKISDURUM { get; set; }
        public string AYLAR { get; set; }
        public Nullable<int> YIL { get; set; }
    }
}
