//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Airlines
    {
        public int ID { get; set; }
        public string MEMBER_CODE_ALPHA { get; set; }
        public string MEMBER_CODE_NUMERIC { get; set; }
        public string COMPANY { get; set; }
        public string COUNTRY { get; set; }
        public string MEMBER_TYPE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> BAGLI_FIRMA_ID { get; set; }
        public string GUNCELLEYEN_KULLANICI { get; set; }
        public string GUNCELLEME_TARIHI { get; set; }
        public string EKLEYEN_KULLANICI { get; set; }
        public string EKLEME_TARIHI { get; set; }
    }
}
