//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TarifeKonteyner
    {
        public int id { get; set; }
        public Nullable<int> TarifeID { get; set; }
        public Nullable<int> TarifeKalemID { get; set; }
        public string Gun { get; set; }
        public string Boy { get; set; }
        public string Tip { get; set; }
        public string Doviz { get; set; }
        public string Fiyat { get; set; }
        public Nullable<int> Kdv { get; set; }
    }
}
