//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AirportWCountryCode
    {
        public int ID { get; set; }
        public string AIRPORT_NAME { get; set; }
        public string IATA_CODE { get; set; }
        public string Country { get; set; }
        public string CCode { get; set; }
        public string UcKod { get; set; }
    }
}
