//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KaraLoads
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> ithihr { get; set; }
        public Nullable<int> PozisyonID { get; set; }
        public string PozisyonNo { get; set; }
        public string LoadNo { get; set; }
        public string txtcmrno { get; set; }
        public string txtcmrtarihi { get; set; }
        public string txtmusteriadi { get; set; }
        public string txtmusteriadikod { get; set; }
        public string txtgonderici { get; set; }
        public string txtgondericikod { get; set; }
        public string OdemeSekli { get; set; }
        public string txtalici { get; set; }
        public string txtalicikod { get; set; }
        public string txturetici { get; set; }
        public string txtureticikod { get; set; }
        public string txtmaladi { get; set; }
        public string txtmaladiyabanci { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtyurtdisiacentekod { get; set; }
        public string txtilkyuklemeyeri { get; set; }
        public string txtilkyuklemeyeritarihi { get; set; }
        public string txtkalkisyeri { get; set; }
        public string txtkalkisyerikod { get; set; }
        public string txtkalkistarihi { get; set; }
        public string txtaktarmayeri { get; set; }
        public string txtaktarmayerikod { get; set; }
        public string txtaktarmatarihi { get; set; }
        public string txtvarisyeri { get; set; }
        public string txtvarisyerikod { get; set; }
        public string txtvaristarihi { get; set; }
        public string txtsonteslimyeri { get; set; }
        public string txtsonteslimtarihi { get; set; }
        public string cmbteslimsekli { get; set; }
        public string txtgumrukyeri { get; set; }
        public string txtgumrukyerikod { get; set; }
        public string txtgumrukluantrepo { get; set; }
        public string txtgumrukluantrepokod { get; set; }
        public string txtmanifestono { get; set; }
        public string txtmanifestotarihi { get; set; }
        public string txtnominasyon { get; set; }
        public string txtsatistipi { get; set; }
        public string toplambrutagirlik { get; set; }
        public string toplamnetagirlik { get; set; }
        public string toplamhacim { get; set; }
        public Nullable<int> toplamkolisayisi { get; set; }
        public string txtnavluntarifesi { get; set; }
        public string cknavluntarifesi { get; set; }
        public string txtdigertarfeler { get; set; }
        public string ckdigertarifeler { get; set; }
        public string ekleyenkullanici { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncellemetarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string toplamkonteyner { get; set; }
        public string markabilgisi { get; set; }
        public string maltanimi { get; set; }
        public string BrutKarZararTL { get; set; }
        public string BrutKarZarar { get; set; }
        public string BrutKarZararEUR { get; set; }
        public string ToplamKarZararTL { get; set; }
        public string ToplamKarZarar { get; set; }
        public string ToplamKarZararEUR { get; set; }
        public string ToplamGiderlerTL { get; set; }
        public string ToplamGiderler { get; set; }
        public string ToplamGiderlerEUR { get; set; }
        public string KdvGiderTL { get; set; }
        public string KdvGider { get; set; }
        public string KdvGiderEUR { get; set; }
        public string FinansGiderTL { get; set; }
        public string FinansGider { get; set; }
        public string FinansGiderEUR { get; set; }
        public string ToplamGelirlerTL { get; set; }
        public string ToplamGelirler { get; set; }
        public string ToplamGelirlerEUR { get; set; }
        public string FinansalGider { get; set; }
        public string FinansalGiderTL { get; set; }
        public string FinansalGiderEUR { get; set; }
        public string KarCiroOrani { get; set; }
        public string TeuAdeti { get; set; }
        public string TeuBasiKarZarar { get; set; }
        public string Kont20adet { get; set; }
        public string Kont40adet { get; set; }
        public string LclWmCbm { get; set; }
        public string LclBasiKarZarar { get; set; }
        public string txtbeyannamekopyasi { get; set; }
        public Nullable<int> RezLoadID { get; set; }
        public string txtaciklama1 { get; set; }
        public string txtaciklama2 { get; set; }
        public string txtaciklama3 { get; set; }
        public string txtaciklama4 { get; set; }
        public string txtaciklama5 { get; set; }
        public string txtaciklama6 { get; set; }
        public string txtaciklama7 { get; set; }
        public Nullable<short> YildizSayisi { get; set; }
        public Nullable<short> YildizSayisi1 { get; set; }
        public Nullable<short> YildizSayisi2 { get; set; }
        public string Yorum { get; set; }
    }
}
