//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Virman
    {
        public int ID { get; set; }
        public Nullable<int> FisID { get; set; }
        public string CariKod { get; set; }
        public string VirmanCariKod { get; set; }
        public string FisDovizTuru { get; set; }
        public string VirmanDovizTuru { get; set; }
        public Nullable<double> Kur { get; set; }
        public Nullable<double> FisTutari { get; set; }
        public Nullable<double> VirmanTutari { get; set; }
        public string Aciklama { get; set; }
    }
}
