//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PozisyonKalemleri
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> Modul { get; set; }
        public Nullable<int> ithihr { get; set; }
        public int PYID { get; set; }
        public Nullable<int> Tur { get; set; }
        public string Durum { get; set; }
        public string KalemAdiEN { get; set; }
        public string KalemAdi { get; set; }
        public string Sube { get; set; }
        public Nullable<int> AB { get; set; }
        public Nullable<bool> Kdvdurum { get; set; }
        public string KdvOrani { get; set; }
        public string RaporGrubu { get; set; }
        public Nullable<int> ith_ihr { get; set; }
        public Nullable<int> Yurtici_disi { get; set; }
        public Nullable<bool> Muhasebe { get; set; }
        public bool sikkullanilan { get; set; }
        public Nullable<bool> Tekrarkesilebilir { get; set; }
        public int Pozisyon { get; set; }
        public string gelirgiderhesabi { get; set; }
        public string kdvhesapno { get; set; }
        public string masrafyeri { get; set; }
        public Nullable<double> miktar { get; set; }
        public string orjinaltutar { get; set; }
        public string DovizKodu { get; set; }
        public string Firmaadi { get; set; }
        public Nullable<int> FirmaKodu { get; set; }
        public string BelgeTarihi { get; set; }
        public string Belgeno { get; set; }
        public string Aratltutari { get; set; }
        public string Kdvtltutari { get; set; }
        public string Orjdoviz { get; set; }
        public string kdvdahiltutar { get; set; }
        public Nullable<bool> SabitKDV { get; set; }
        public string islemtarihi { get; set; }
        public string faturadoviztutari { get; set; }
        public string faturadovizkodu { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
        public Nullable<int> KalemID { get; set; }
        public Nullable<int> DagitimKalemi { get; set; }
        public Nullable<int> DagitimSira { get; set; }
        public string OzelKodu { get; set; }
        public Nullable<int> Dagitildi { get; set; }
        public Nullable<int> BagliPozKalemID { get; set; }
        public Nullable<int> DemurajKontID { get; set; }
        public string BaglantiYeri1 { get; set; }
        public Nullable<int> TalimatID { get; set; }
        public Nullable<int> HataGizle { get; set; }
        public Nullable<int> KalemTipi { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public string FaturaAciklama { get; set; }
    }
}
