//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Overseas_Invoice
    {
        public int ID { get; set; }
        public string FILENAME { get; set; }
        public string FILE_EXT { get; set; }
        public string POSITION_NR { get; set; }
        public string DOCNR { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> CREATED_BY_ID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> SENT_TO_ID { get; set; }
        public string SENT_TO { get; set; }
        public Nullable<System.DateTime> SENT_ON { get; set; }
        public Nullable<int> APPROVED_BY_ID { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_ON { get; set; }
        public Nullable<int> ARCHIVED_BY_ID { get; set; }
        public string ARCHIVED_BY { get; set; }
        public Nullable<System.DateTime> ARCHIVED_BY_ON { get; set; }
    }
}
