//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProjePozisyonlar
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string pozno { get; set; }
        public string pozisyonno { get; set; }
        public string txtsube { get; set; }
        public string txtistipi { get; set; }
        public string txtopgrup { get; set; }
        public string txtacilistarihi { get; set; }
        public string txtacilistarihilong { get; set; }
        public string txtkapanistarihi { get; set; }
        public string Musteriadi { get; set; }
        public string MusteriKodu { get; set; }
        public string txtbeklenenvaristar { get; set; }
        public string txtkalkistarihi { get; set; }
        public string txtvaristarihi { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtyuklemelimanitar { get; set; }
        public string txtaktarmalimani { get; set; }
        public string txtaktarmalimanitar { get; set; }
        public string txttahliyelimani { get; set; }
        public string txttahliyelimanitarihi { get; set; }
        public string txtyuklemelimanikod { get; set; }
        public string txttahliyelimanikod { get; set; }
        public string toplambrutagirlik { get; set; }
        public string toplamnetagirlik { get; set; }
        public string toplamhacim { get; set; }
        public Nullable<int> toplamkolisayisi { get; set; }
        public string toplamkonteyner { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
    }
}
