//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kunye_User_Match
    {
        public int ID { get; set; }
        public Nullable<int> PAKETID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> BASLANGIC { get; set; }
        public Nullable<System.DateTime> BITIS { get; set; }
        public string TANIMLAYAN { get; set; }
        public Nullable<System.DateTime> TANIMLAMA_TARIHI { get; set; }
    }
}
