//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FreightRequestResponseItems
    {
        public int id { get; set; }
        public Nullable<int> Modul { get; set; }
        public Nullable<int> FreightID { get; set; }
        public Nullable<int> ResponseID { get; set; }
        public string Status { get; set; }
        public string ItemNameEN { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> AB { get; set; }
        public Nullable<bool> VATStatus { get; set; }
        public string VATRate { get; set; }
        public Nullable<bool> Accounting { get; set; }
        public Nullable<bool> CanbeCutAgain { get; set; }
        public string IncomeExpenseAccount { get; set; }
        public string VATAccountNo { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> OriginalAmount { get; set; }
        public string ExchangeCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public string DocumentDate { get; set; }
        public Nullable<double> IntermediateTLAmount { get; set; }
        public Nullable<double> VATTLAmount { get; set; }
        public string OriginalCurrency { get; set; }
        public Nullable<double> AmountIncludingVAT { get; set; }
        public Nullable<bool> FixedVAT { get; set; }
        public string TransactionDate { get; set; }
        public Nullable<double> InvoiceCurrencyAmount { get; set; }
        public string InvoiceCurrencyCode { get; set; }
        public string AddedUser { get; set; }
        public string AddDate { get; set; }
        public string UpdatingUser { get; set; }
        public string DateofUpdate { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> DistributionItem { get; set; }
        public Nullable<int> DistributionRow { get; set; }
        public Nullable<int> Distribute { get; set; }
        public Nullable<int> ConnectedPosItemID { get; set; }
        public Nullable<int> ItemType { get; set; }
    }
}
