//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Quote_Cargo_Detail
    {
        public int ID { get; set; }
        public Nullable<int> QUOTEID { get; set; }
        public string MalAdi { get; set; }
        public Nullable<int> BirimAdet { get; set; }
        public string KonteynerBoyu { get; set; }
        public string KonteynerSekli { get; set; }
        public Nullable<int> PaketSayisi { get; set; }
        public string PaketSekli { get; set; }
        public Nullable<double> Boy { get; set; }
        public Nullable<double> En { get; set; }
        public Nullable<double> Yukseklik { get; set; }
        public Nullable<double> BirimHacim { get; set; }
        public Nullable<double> BirimNetAgirlik { get; set; }
        public Nullable<double> BirimBrutAgirlik { get; set; }
        public Nullable<double> Hacim { get; set; }
        public Nullable<double> NetAgirlik { get; set; }
        public Nullable<double> BrutAgirlik { get; set; }
        public Nullable<double> NavlunAgirlik { get; set; }
        public string Aciklama { get; set; }
    }
}
