//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Purchase_Items
    {
        public int ID { get; set; }
        public Nullable<int> PURCHASE_FORM_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string PROPERTIESANDTYPE { get; set; }
        public string QUANTITYANDMEASURE { get; set; }
        public string JUSTIFICATION { get; set; }
    }
}
