//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AirportsWCountry
    {
        public int ID { get; set; }
        public string AIRPORT_NAME { get; set; }
        public string AIRPORT_CITY { get; set; }
        public string AIRPORT_COUNTRY { get; set; }
        public string IATA_CODE { get; set; }
        public Nullable<int> NON_EAWB { get; set; }
        public Nullable<int> AgencyConnection { get; set; }
        public string COUNTRY { get; set; }
    }
}
