//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TradeItems
    {
        public int id { get; set; }
        public Nullable<int> TradeID { get; set; }
        public string YukNo { get; set; }
        public string txtcommodity { get; set; }
        public string txtdensity { get; set; }
        public string txtnetweight { get; set; }
        public string txtgrossweight { get; set; }
        public string txtbulkquantity { get; set; }
        public string txtloadingdate { get; set; }
        public string txtsailingdate { get; set; }
        public string txtdischargingdate { get; set; }
        public string txtflexitankno { get; set; }
        public string txtcontainerno { get; set; }
        public string txtsealno { get; set; }
        public string txtplateno { get; set; }
        public string txttowtruckplateno { get; set; }
        public string txtdrivername { get; set; }
        public string txtproperty { get; set; }
        public string txtloadingplace { get; set; }
        public string txtdischargeplace { get; set; }
        public string txtbatirefno { get; set; }
        public string txtvessel { get; set; }
        public string txtvesselkod { get; set; }
        public string Buyingunitprice { get; set; }
        public string Sellingunitprice { get; set; }
    }
}
