//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LINE_TEU_REPORT
    {
        public long RowNo { get; set; }
        public string FIRMANO { get; set; }
        public string HATADI { get; set; }
        public Nullable<int> İTHALAT_İHRACAT { get; set; }
        public string ŞUBE { get; set; }
        public Nullable<double> TEUADETI { get; set; }
        public string YIL { get; set; }
    }
}
