//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ports
    {
        public int id { get; set; }
        public string PortCode { get; set; }
        public string PortName { get; set; }
        public string Region { get; set; }
        public string CCode { get; set; }
    }
}
