//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Infinity_Menu
    {
        public int ID { get; set; }
        public string Title_TR { get; set; }
        public string Title_EN { get; set; }
        public string Title_DEU { get; set; }
        public Nullable<int> SahipID { get; set; }
        public string Aciklama { get; set; }
        public string Link { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string İcon { get; set; }
        public Nullable<int> User_Type { get; set; }
    }
}
