//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Performances_MatchTable
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserManagerID { get; set; }
        public Nullable<int> PerformanceID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Updater { get; set; }
    }
}
