//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PendingList
    {
        public int id { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Section { get; set; }
        public string Process { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ProcessID { get; set; }
    }
}
