//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_isotank
    {
        public int id { get; set; }
        public string txttankowner { get; set; }
        public string txtisotanknr { get; set; }
        public string txttare { get; set; }
        public string txttanksize { get; set; }
        public string cmbstatus { get; set; }
        public string txtwhereami { get; set; }
        public string txtsoftfilenr { get; set; }
        public string txtagentrefnr { get; set; }
        public string txtshipper { get; set; }
        public string txtcnee { get; set; }
        public Nullable<int> cneeid { get; set; }
        public string txtshipperref { get; set; }
        public string txtcneeref { get; set; }
        public string txtlessorcompany { get; set; }
        public string txtleasecontractnr { get; set; }
        public string txtleasecontractdate { get; set; }
        public string txtleaseexpiredate { get; set; }
        public string txttypeofequipment { get; set; }
        public string txtmaxgrossweight { get; set; }
        public string txtleasedeliveryplace { get; set; }
        public string txtleaseredeliveryplace { get; set; }
        public string txtnexthydrolictest { get; set; }
        public string txtnextairtest { get; set; }
        public string txttankmaterial { get; set; }
        public string txtdischargelocation { get; set; }
        public string txtondate { get; set; }
        public string txtoffdate { get; set; }
        public Nullable<int> rshandrail { get; set; }
        public string txtdailyhirerate { get; set; }
        public string txtworkingpreasure { get; set; }
        public string txttestpreasure { get; set; }
        public string txtline { get; set; }
        public string txtvasselname { get; set; }
        public string txtvoyage { get; set; }
        public string txtfvesselname { get; set; }
        public string txtvoyagenr { get; set; }
        public string txtportofloading { get; set; }
        public string txtviaport { get; set; }
        public string txtportofdischarge { get; set; }
        public string txtfinaldelivery { get; set; }
        public string txtnetweight { get; set; }
        public string txtbulk { get; set; }
        public string txtloadingdate { get; set; }
        public string txtloadingplace { get; set; }
        public string txtcutoff { get; set; }
        public string txtets { get; set; }
        public string txtviaeta { get; set; }
        public string txteta { get; set; }
        public string txtimco { get; set; }
        public string txtunno { get; set; }
        public string txtfp { get; set; }
        public string txtpg { get; set; }
        public string ckhazardous { get; set; }
        public string txtcargodensity { get; set; }
        public string txttruckingdates { get; set; }
        public string txtcneedischarge { get; set; }
        public string txtemptyportreturndate { get; set; }
        public string txtdemurrage { get; set; }
        public string txtchargebleadays { get; set; }
        public string txtdemurrageamount { get; set; }
        public string txtminloadingweight { get; set; }
        public string txtmaxloadingweight { get; set; }
        public string txtexportshipline { get; set; }
        public string txtexportvesselname { get; set; }
        public string txtexportvoyagenr { get; set; }
        public string txtexportvessel { get; set; }
        public string txtexpvoyage { get; set; }
        public string txtexppol { get; set; }
        public string txtexpviaportof { get; set; }
        public string txtexppod { get; set; }
        public string txtexpfinaldelivery { get; set; }
        public string txtexpnetweight { get; set; }
        public string txtexpbulk { get; set; }
        public string txtexpld { get; set; }
        public string txtexplp { get; set; }
        public string txtmscref { get; set; }
        public string txtblnr { get; set; }
        public string txtexpcutoff { get; set; }
        public string txtexpets { get; set; }
        public string txtexpviaeta { get; set; }
        public string txtexpeta { get; set; }
        public string txtexpimco { get; set; }
        public string txtexpunno { get; set; }
        public string txtexppg { get; set; }
        public string txtexpfp { get; set; }
        public string ckexphazardous { get; set; }
        public string txtexpcargodensity { get; set; }
        public string txtexptruckingdate { get; set; }
        public string txtexpcneedd { get; set; }
        public string txtexpportreturndate { get; set; }
        public string txtexpdemurragetariff { get; set; }
        public string txtexpchargebledays { get; set; }
        public string txtexpdemurrageamount { get; set; }
        public string txtexpminloadingweight { get; set; }
        public string txtexpmaxloadingweight { get; set; }
        public string Updater { get; set; }
        public string UpdaterTime { get; set; }
        public string CreationTime { get; set; }
        public string txtexpshipper { get; set; }
        public string txtexpcnee { get; set; }
        public Nullable<int> DeleteStatus { get; set; }
    }
}
