//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Degerler
    {
        public int id { get; set; }
        public string kod { get; set; }
        public string deger1 { get; set; }
        public Nullable<double> deger2 { get; set; }
        public string deger3 { get; set; }
        public string deger4 { get; set; }
        public string deger5 { get; set; }
        public string deger6 { get; set; }
        public string deger7 { get; set; }
        public string deger8 { get; set; }
        public string deger9 { get; set; }
        public string deger10 { get; set; }
        public string deger11 { get; set; }
        public string kodgrubu { get; set; }
        public string Ekleyen { get; set; }
        public Nullable<System.DateTime> Tarihi { get; set; }
        public Nullable<System.DateTime> Saati { get; set; }
        public string guncelleyen { get; set; }
        public Nullable<System.DateTime> GuncTarih { get; set; }
        public Nullable<System.DateTime> GuncSaat { get; set; }
        public string alanadi { get; set; }
    }
}
