//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AuthorizeUsers
    {
        public int id { get; set; }
        public Nullable<int> AuthorizeUser1 { get; set; }
        public string AuthorizeUserName1 { get; set; }
        public Nullable<int> AuthorizeUser2 { get; set; }
        public string AuthorizeUserName2 { get; set; }
        public Nullable<int> AuthorizeUser3 { get; set; }
        public string AuthorizeUserName3 { get; set; }
        public Nullable<int> AuthorizeUser4 { get; set; }
        public string AuthorizeUserName4 { get; set; }
        public Nullable<int> BranchNo { get; set; }
    }
}
