//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EvrakSablonIstipi
    {
        public int id { get; set; }
        public Nullable<int> Evrak_ID { get; set; }
        public string Evrak_Adi { get; set; }
        public string IsTipi { get; set; }
    }
}
