//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Logo_Donemler
    {
        public int id { get; set; }
        public Nullable<int> FirmaNo { get; set; }
        public string Donem { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> MGLFirma { get; set; }
    }
}
