//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HavaRezervasyonlar
    {
        public int id { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string FirmaNo { get; set; }
        public string PozisyonNo { get; set; }
        public string txtistipi { get; set; }
        public string txtsube { get; set; }
        public string txtopgrup { get; set; }
        public string txtrezervasyontarihi { get; set; }
        public Nullable<int> RezerveDurum { get; set; }
        public string txtmusteriadi { get; set; }
        public string txtmusteriadikod { get; set; }
        public string txturetici { get; set; }
        public string txtureticikod { get; set; }
        public string txtgonderici { get; set; }
        public string txtgondericikod { get; set; }
        public string txttahliyelimani { get; set; }
        public string txttahliyelimanikod { get; set; }
        public string txtnihaivaris { get; set; }
        public string txtnihaivariskod { get; set; }
        public string txtpostakodu { get; set; }
        public string txtparcasayisi { get; set; }
        public string txtagirlik { get; set; }
        public string txthacim { get; set; }
        public string txtmuhtemelteslimtarihi { get; set; }
        public string txtbeklenenvaristarihi { get; set; }
        public string txtmalbedeli { get; set; }
        public string txtmalcinsi { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtyurtdisiacentekod { get; set; }
        public string txtmerkezacente { get; set; }
        public string txtmerkezacentekod { get; set; }
        public string txthawbno { get; set; }
        public string txthawbtarihi { get; set; }
        public string txtilkyuklemeyeri { get; set; }
        public string txtilkyuklemeyerikod { get; set; }
        public string txtcikislimani { get; set; }
        public string txtcikislimanikod { get; set; }
        public string txtalici { get; set; }
        public string txtalicikod { get; set; }
        public string txtbanka { get; set; }
        public string txtbankakod { get; set; }
        public string txtnotify { get; set; }
        public string txtnotifykod { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public string GuncellemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
        public string EklemeTarihi { get; set; }
    }
}
