//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DemurajFiyatlari
    {
        public int id { get; set; }
        public Nullable<int> gun { get; set; }
        public string konteynertipi { get; set; }
        public string yirmilik { get; set; }
        public string kirklik { get; set; }
        public Nullable<int> Did { get; set; }
    }
}
