//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HsCodes
    {
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string HS_CODE { get; set; }
        public string HS_DESC { get; set; }
        public string UNIT { get; set; }
        public string TAX { get; set; }
    }
}
