//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Traxon_OutBox
    {
        public int ID { get; set; }
        public string FILENAME { get; set; }
        public string FILE_CONTENT { get; set; }
        public string MAWB_NO { get; set; }
        public string AIRLINE_PREFIX { get; set; }
        public string AWB_SERIAL_NO { get; set; }
        public string DEPARTURE_CITY_CODE { get; set; }
        public string ARRIVAL_CITY_CODE { get; set; }
        public Nullable<double> NO_OF_PIECES { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> TOTAL_NO_OF_PIECES { get; set; }
        public string STATUS_DESC { get; set; }
        public string STATUS_CODE { get; set; }
        public string STATUS_CARRIER_CODE { get; set; }
        public string STATUS_DAY { get; set; }
        public string STATUS_MONTH { get; set; }
        public string STATUS_TIME { get; set; }
        public string STATUS_AIRPORT_CODE { get; set; }
        public Nullable<double> STATUS_NOP { get; set; }
        public Nullable<double> STATUS_WEIGHT { get; set; }
        public string STATUS_TIMEOFDEPARTURE { get; set; }
        public string STATUS_TIMEOFARRIVAL { get; set; }
        public Nullable<System.DateTime> MSG_CREATION_TIME { get; set; }
    }
}
