//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Flexi_Seri
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SubeNo { get; set; }
        public string FlexiSira { get; set; }
        public string FlexiNO { get; set; }
        public string Kapasite { get; set; }
        public string DolumTuru { get; set; }
        public string HortumTuru { get; set; }
        public string Marka { get; set; }
        public Nullable<System.DateTime> AlisTarihi { get; set; }
        public Nullable<System.DateTime> UretimTarihi { get; set; }
        public Nullable<int> VanaInc { get; set; }
        public Nullable<int> FlexiSayisi { get; set; }
        public string BeyannameNo { get; set; }
        public string Baslangic { get; set; }
        public string Bitis { get; set; }
        public Nullable<int> Durum { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
    }
}
