//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Proje_All
    {
        public int id { get; set; }
        public Nullable<int> Tasima { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> Loadid { get; set; }
        public string LoadNo { get; set; }
        public string txthblno { get; set; }
        public string txthbltarihi { get; set; }
        public string toplamkonteyner { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txttahliyelimani { get; set; }
        public string txtmusteriadi { get; set; }
        public string ilkkonteynerno { get; set; }
        public string txtgonderici { get; set; }
        public string txtalici { get; set; }
        public Nullable<int> toplamkolisayisi { get; set; }
        public string toplamhacim { get; set; }
        public string toplambrutagirlik { get; set; }
        public string txtistipi { get; set; }
        public string txtsube { get; set; }
        public string txtopgrup { get; set; }
        public string cmbteslimsekli { get; set; }
        public string txtyuklemeyeri { get; set; }
        public string txtnihaimevrit { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public Nullable<int> Pid { get; set; }
        public string pozpozno { get; set; }
        public string HatAdi { get; set; }
        public string acilistar { get; set; }
        public string kapanistar { get; set; }
        public string pozno { get; set; }
        public string OdemeSekli { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string txtmblno { get; set; }
        public string txtmusteriadikod { get; set; }
        public string txtgondericikod { get; set; }
        public string txtalicikod { get; set; }
        public string txtyuklemegemisi { get; set; }
        public string txtyuklemegemisikod { get; set; }
        public string txtyuklemelimanikod { get; set; }
        public string txttahliyelimanikod { get; set; }
        public string txtyurtdisigemiacentesi { get; set; }
        public string txtyurtdisigemiacentesikod { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtyurtdisiacentekod { get; set; }
        public string txthatkod { get; set; }
        public string kapatxtacilistarihinistar { get; set; }
        public string txtyukdurum { get; set; }
    }
}
