//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Envanter
    {
        public int ID { get; set; }
        public string EnvanterAdi { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<int> Yil { get; set; }
        public string No { get; set; }
        public string Aciklama { get; set; }
        public string EkleyenKullanici { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<int> BagliKullanici { get; set; }
    }
}
