//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_YonetmeEslestirme
    {
        public int id { get; set; }
        public Nullable<int> YonetenID { get; set; }
        public Nullable<int> YonetilenID { get; set; }
        public Nullable<int> UserType { get; set; }
    }
}
