//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MCode_Request
    {
        public int MCode_Request_ID { get; set; }
        public Nullable<int> Gonderen_Kullanici_ID { get; set; }
        public string Gonderen_Adi_Soyadi { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public string Firma_Adi { get; set; }
        public Nullable<int> M_Code_Durum { get; set; }
        public Nullable<System.DateTime> M_Code_IstekTarihi { get; set; }
        public Nullable<System.DateTime> M_Code_OnayTarihi { get; set; }
        public string Onaylayan_Adi_Soyadi { get; set; }
        public Nullable<int> Onaylayan_Kullanici_ID { get; set; }
        public string Iptal_Aciklama { get; set; }
    }
}
