//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FreightRequest
    {
        public int id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string LoadingPortCode { get; set; }
        public string LoadingPortName { get; set; }
        public string LoadingCountryCode { get; set; }
        public string LoadingCountry { get; set; }
        public string ArrivalPortCode { get; set; }
        public string ArrivalPortName { get; set; }
        public string ArrivalCountryCode { get; set; }
        public string ArrivalCountry { get; set; }
        public string InstallationLocation { get; set; }
        public string DeliveryLocation { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public string ContainerLength { get; set; }
        public string ContainerType { get; set; }
        public string ContainerOwner { get; set; }
        public Nullable<System.DateTime> ReadyDate { get; set; }
        public Nullable<decimal> Tonnage { get; set; }
        public string TypeofGoods { get; set; }
        public string GoodsName { get; set; }
        public Nullable<System.DateTime> AvailabilityDate { get; set; }
        public string Incoterm { get; set; }
        public string Notes { get; set; }
        public string Imo { get; set; }
        public string FilePath { get; set; }
        public string FreetimeRequest { get; set; }
        public string DestinationFreight { get; set; }
        public string AdditionalNotes { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public string UpdatingUser { get; set; }
        public Nullable<System.DateTime> DateofUpdate { get; set; }
        public Nullable<int> AddedUserId { get; set; }
        public string AddedUser { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> ApprovedUserId { get; set; }
        public string ApprovingUser { get; set; }
        public Nullable<System.DateTime> ApprovedUserDate { get; set; }
    }
}
