//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rezervasyon_Deniz
    {
        public int id { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string FirmaNo { get; set; }
        public string Rezervasyon_No { get; set; }
        public string pozno { get; set; }
        public string txtistipi { get; set; }
        public string txtsube { get; set; }
        public string txtacilistarihi { get; set; }
        public string txtacilistarihilong { get; set; }
        public string txtonaytarihi { get; set; }
        public string cmbmblodeme { get; set; }
        public string cmbhblodeme { get; set; }
        public string txtnominasyon { get; set; }
        public string txthbltarihi { get; set; }
        public string txtmusteriadi { get; set; }
        public string txtmusteriadikod { get; set; }
        public string txtgonderici { get; set; }
        public string txtgondericikod { get; set; }
        public string txtalici { get; set; }
        public string txtalicikod { get; set; }
        public string txtmaladiyabanci { get; set; }
        public string txtyuklemegemisi { get; set; }
        public string txtyuklemegemisikod { get; set; }
        public string txtyuklemegemisiseferno { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtyurtdisiacentekod { get; set; }
        public string txthat { get; set; }
        public string txthatkod { get; set; }
        public string txtyurticigemiacentesi { get; set; }
        public string txtyurticigemiacentesikod { get; set; }
        public string txtyuklemeyeri { get; set; }
        public string txtyuklemeyerikod { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtyuklemelimanikod { get; set; }
        public string txttahliyelimani { get; set; }
        public string txttahliyelimanikod { get; set; }
        public string txtnihaimevrit { get; set; }
        public string txtnihaimevritkod { get; set; }
        public string txtyuklemetarihi { get; set; }
        public string toplamkonteyner { get; set; }
        public Nullable<int> linerbl { get; set; }
        public string ekbilgi { get; set; }
        public string TahsilatSekli { get; set; }
        public Nullable<int> VadeGun { get; set; }
        public string cmbincoterms { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public Nullable<int> Rezervasyon_Durum { get; set; }
        public string Rezervasyon_Mesajı { get; set; }
        public string Kime { get; set; }
        public string Onaylayan { get; set; }
        public string Onay_Tarihi { get; set; }
        public string KarsiPozisyonNo { get; set; }
    }
}
