//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Traxon_Hbl
    {
        public int ID { get; set; }
        public Nullable<int> DOCID { get; set; }
        public string DEPARTURE_CODE { get; set; }
        public string ARRIVAL_CODE { get; set; }
        public string HWBNO { get; set; }
        public Nullable<double> PKGS { get; set; }
        public Nullable<double> WT_KGS { get; set; }
        public string SHIPPER_NAME { get; set; }
        public string SHIPPER_ADDRESS { get; set; }
        public string SHIPPER_CITY { get; set; }
        public string SHIPPER_COUNTRY_CODE { get; set; }
        public string SHIPPER_ZIP { get; set; }
        public string SHIPPER_TAX { get; set; }
        public string CONSIGNEE_NAME { get; set; }
        public string CONSIGNEE_ADDRESS { get; set; }
        public string CONSIGNEE_CITY { get; set; }
        public string CONSIGNEE_COUNTRY_CODE { get; set; }
        public string CONSIGNEE_ZIP { get; set; }
        public string CONSIGNEE_TAX { get; set; }
        public string HANDLING_INFO { get; set; }
        public string DESCRIPTION { get; set; }
        public string FREE_TEXT { get; set; }
        public string HTS { get; set; }
        public string FREIGHT_TERM { get; set; }
        public string COMPLETE_MSG { get; set; }
        public Nullable<int> PAPER_BL { get; set; }
        public string ADDITIONAL_TEXT { get; set; }
    }
}
