//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_StokView
    {
        public int SeriID { get; set; }
        public Nullable<int> HavayoluID { get; set; }
        public Nullable<int> SubeNo { get; set; }
        public string AwbNO { get; set; }
        public string AlisTarihi { get; set; }
        public Nullable<int> AwbSayisi { get; set; }
        public string CikisLimani { get; set; }
        public string CikisLimaniKodu { get; set; }
        public string Baslangicno { get; set; }
        public string Bitisno { get; set; }
        public Nullable<int> RezervasyonID { get; set; }
        public string Durum { get; set; }
        public Nullable<int> RezID { get; set; }
        public string pozisyonno { get; set; }
        public string pozno { get; set; }
        public string txtmblno { get; set; }
        public string txtmbltarihi { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtyuklemelimanitar { get; set; }
        public string txttahliyelimani { get; set; }
        public string txttahliyelimanitarihi { get; set; }
        public string txtyuklemegemisiseferno { get; set; }
        public string toplamhacim { get; set; }
        public string toplambrutagirlik { get; set; }
        public Nullable<int> toplamkolisayisi { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtopgrup { get; set; }
        public string txtsube { get; set; }
        public string txthat { get; set; }
        public string txtistipi { get; set; }
        public string txtkalkistarihi { get; set; }
        public string txtvaristarihi { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
        public string txtacilistarihi { get; set; }
        public string txtkapanistarihi { get; set; }
        public string txtacilistarihilong { get; set; }
        public string txtyuklemelimanikod { get; set; }
        public string txttahliyelimanikod { get; set; }
        public string txtyurtdisiacentekod { get; set; }
        public Nullable<int> id { get; set; }
        public string RezPozisyonNo { get; set; }
        public string Rezpozno { get; set; }
        public string Reztxtmblno { get; set; }
        public string Reztxtmbltarihi { get; set; }
        public string Reztxtyuklemelimani { get; set; }
        public string Reztxtyuklemelimanitar { get; set; }
        public string Reztxttahliyelimani { get; set; }
        public string Reztxttahliyelimanitarihi { get; set; }
        public string Reztxtyuklemegemisiseferno { get; set; }
        public string Reztoplamhacim { get; set; }
        public string Reztoplambrutagirlik { get; set; }
        public Nullable<int> Reztoplamkolisayisi { get; set; }
        public string Reztxtyurtdisiacente { get; set; }
        public string Reztxtopgrup { get; set; }
        public string Reztxtsube { get; set; }
        public string Reztxthat { get; set; }
        public string Reztxtistipi { get; set; }
        public string Reztxtkalkistarihi { get; set; }
        public string Reztxtvaristarihi { get; set; }
        public string Reztxtacilistarihi { get; set; }
        public string Reztxtkapanistarihi { get; set; }
        public string Reztxtacilistarihilong { get; set; }
        public string Reztxtyuklemelimanikod { get; set; }
        public string Reztxttahliyelimanikod { get; set; }
        public string Reztxtyurtdisiacentekod { get; set; }
        public string Rezguncelleyenkullanici { get; set; }
        public string Rezguncellemetarihi { get; set; }
        public string Rezekleyenkullanici { get; set; }
        public string Rezeklemetarihi { get; set; }
        public string FirmaNo { get; set; }
    }
}
