//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KayitliTeklifKalemleri
    {
        public int id { get; set; }
        public Nullable<int> TeklifID { get; set; }
        public Nullable<int> KalemID { get; set; }
        public string AB { get; set; }
        public string KalemAdi { get; set; }
        public string Doviz { get; set; }
        public string Fiyat { get; set; }
        public Nullable<int> Kdv { get; set; }
    }
}
