//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MeetingCustomer
    {
        public int id { get; set; }
        public Nullable<int> MeetingID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string NameSurname { get; set; }
        public string Title { get; set; }
    }
}
