//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MalzemeListesi
    {
        public int ID { get; set; }
        public string KODU { get; set; }
        public string MALZEME_ADI { get; set; }
        public string GTIP_KODU { get; set; }
        public Nullable<double> STOK_MIKTARI { get; set; }
        public Nullable<int> KDV_ORANI { get; set; }
        public string MUHASEBE_BAGLANTI { get; set; }
        public Nullable<int> LOGO_AKTARIM { get; set; }
        public string AKTARIM_HATA { get; set; }
    }
}
