//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SeyahatFormlari
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CikisTarihi { get; set; }
        public string DonusTarihi { get; set; }
        public string FaturaSirketi { get; set; }
        public string GidilenSehir { get; set; }
        public string Arac { get; set; }
        public string SeyahatNedeni { get; set; }
        public string gecelemevarmi { get; set; }
        public string kacgece { get; set; }
        public string arackacgun { get; set; }
        public string arackiralamavarmi { get; set; }
        public string arackiralamakacgun { get; set; }
        public string oteladi { get; set; }
        public string avansvarmi { get; set; }
        public string miktar { get; set; }
        public string KayitTarihi { get; set; }
        public string Onaylayan { get; set; }
        public string OnaylamaTarihi { get; set; }
        public Nullable<int> onaydurum { get; set; }
    }
}
