//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Countries
    {
        public int id { get; set; }
        public string CCode { get; set; }
        public string Country { get; set; }
        public string CTelCode { get; set; }
        public Nullable<int> EU_Member { get; set; }
        public string UcKod { get; set; }
    }
}
