//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TankPositions
    {
        public int id { get; set; }
        public string txttankowner { get; set; }
        public string txtisotanknr { get; set; }
        public string txttare { get; set; }
        public string txttanksize { get; set; }
        public string txtlessorcompany { get; set; }
        public string txtleasecontractnr { get; set; }
        public string txtleasecontractdate { get; set; }
        public string txtleaseexpiredate { get; set; }
        public string txtleasedeliveryplace { get; set; }
        public string txtleaseredeliveryplace { get; set; }
        public string txtnexthydrolictest { get; set; }
        public string txtnextairtest { get; set; }
        public string txtondate { get; set; }
        public string txtoffdate { get; set; }
        public Nullable<int> rshandrail { get; set; }
        public string txtdailyhirerate { get; set; }
        public string txttypeofequipment { get; set; }
        public string txtmaxgrossweight { get; set; }
        public string txttankmaterial { get; set; }
        public string txtdischargelocation { get; set; }
        public string txtworkingpreasure { get; set; }
        public string txttestpreasure { get; set; }
    }
}
