//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Branches
    {
        public int id { get; set; }
        public string txtsube { get; set; }
        public string txtphone { get; set; }
        public string txtfax { get; set; }
        public string txtcountrycode { get; set; }
        public string txtcountry { get; set; }
        public string txtcitycode { get; set; }
        public string txtcity { get; set; }
        public string txtaddress1 { get; set; }
        public string txtaddress { get; set; }
        public Nullable<int> FirmID { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public string GuncellemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
        public string EklemeTarihi { get; set; }
    }
}
