//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Denizyolu_Ticari
    {
        public int id { get; set; }
        public Nullable<int> YukID { get; set; }
        public string cmbtransporttype { get; set; }
        public string txtvessel { get; set; }
        public string txtvesselkod { get; set; }
        public string txtcustomsorder { get; set; }
        public string txtcustomsorderkod { get; set; }
        public string txtsiparisno { get; set; }
        public string txtsiparistarihi { get; set; }
        public string kur { get; set; }
        public string txtsevkiyatno { get; set; }
        public string txthacim { get; set; }
        public string txtyogunluk { get; set; }
        public string txtnetagirlik { get; set; }
        public string txtbrutagirlik { get; set; }
        public string txturunkodu { get; set; }
        public string txtdorseplakano { get; set; }
        public string txtcekiciplakano { get; set; }
        public string txtflexitankno { get; set; }
        public string txtflexitanktipi { get; set; }
        public string txticnakliyefirmasi { get; set; }
        public string txtsurucuadisoyadi { get; set; }
        public string txtmaltanimi { get; set; }
        public string txtsatisbirimfiyati { get; set; }
        public string txtalisbirimfiyati { get; set; }
        public string txtotvalisorani { get; set; }
        public string txtkdvalisorani { get; set; }
        public string txtsigortabedeli { get; set; }
        public string txtpoliceno { get; set; }
        public string txtnavlunbedeli { get; set; }
    }
}
