//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KoliBilgileri
    {
        public int KoliID { get; set; }
        public Nullable<int> ModulID { get; set; }
        public Nullable<int> PozisyonID { get; set; }
        public Nullable<int> YukID { get; set; }
        public Nullable<int> KonteynerID { get; set; }
        public string MalAdi { get; set; }
        public string PaketSekli { get; set; }
        public Nullable<int> KoliSayisi { get; set; }
        public Nullable<double> NavlunAgirlik { get; set; }
        public Nullable<double> NetAgirlik { get; set; }
        public Nullable<double> BirimNetAgirlik { get; set; }
        public Nullable<double> BrutAgirlik { get; set; }
        public Nullable<double> BirimBrutAgirlik { get; set; }
        public Nullable<double> Hacim { get; set; }
        public Nullable<double> BirimHacim { get; set; }
        public Nullable<int> En { get; set; }
        public Nullable<int> Boy { get; set; }
        public Nullable<int> Yukseklik { get; set; }
    }
}
