//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Trades
    {
        public int id { get; set; }
        public string PozNo { get; set; }
        public string PozisyonNo { get; set; }
        public string txtistipi { get; set; }
        public string txtacilistarihi { get; set; }
        public string txtsube { get; set; }
        public string txtkapanistarihi { get; set; }
        public string Producer { get; set; }
        public string Cnee { get; set; }
        public string Shipper { get; set; }
        public string Receiver { get; set; }
        public string BatiRefno { get; set; }
        public string SoftFileno { get; set; }
        public string txtblno { get; set; }
        public string Buyingunitprice { get; set; }
        public string Sellingunitprice { get; set; }
        public string Transporttype { get; set; }
        public string CustomBroker { get; set; }
        public string vessel { get; set; }
        public string txtloadingvessel { get; set; }
        public string txtvoyagenr { get; set; }
        public string txtportofdischarge { get; set; }
        public string txtportofloading { get; set; }
        public string itemshipper1 { get; set; }
        public string itemshipper2 { get; set; }
        public string itemshipper3 { get; set; }
        public string itemshipper4 { get; set; }
        public string itemshipper5 { get; set; }
        public string itemshipper6 { get; set; }
        public string itemshipper7 { get; set; }
        public string itemreceiver1 { get; set; }
        public string itemreceiver2 { get; set; }
        public string itemreceiver3 { get; set; }
        public string itemreceiver4 { get; set; }
        public string itemreceiver5 { get; set; }
        public string itemreceiver6 { get; set; }
        public string itemreceiver7 { get; set; }
        public string itemcustombroker1 { get; set; }
        public string itemcustombroker2 { get; set; }
        public string itemcustombroker3 { get; set; }
        public string itemcustombroker4 { get; set; }
        public string itemcustombroker5 { get; set; }
        public string itemcustombroker6 { get; set; }
        public string itemcustombroker7 { get; set; }
        public string itemvessel1 { get; set; }
        public string itemvessel2 { get; set; }
        public string txtexitcustoms { get; set; }
        public string txtinsurance { get; set; }
        public string txtfreight { get; set; }
        public string txtaciklama { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public string GuncellemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
        public string EklemeTarihi { get; set; }
        public string txtproducerkod { get; set; }
        public string txtshipperkod { get; set; }
        public string txtcneekod { get; set; }
        public string txtreceiverkod { get; set; }
        public string txtvesselkod { get; set; }
        public string txtloadingvesselkod { get; set; }
        public string txtportofloadingkod { get; set; }
        public string txtportofdischargekod { get; set; }
        public string txtcustombrokerkod { get; set; }
    }
}
