//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FaturaSayaclar
    {
        public int id { get; set; }
        public string SeriNo { get; set; }
        public string FirmaNo { get; set; }
        public string SayacBaslangic { get; set; }
        public Nullable<long> SayacNo { get; set; }
        public string Modul { get; set; }
        public Nullable<int> FaturaYil { get; set; }
    }
}
