//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OdemeTalimatlari
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Sube { get; set; }
        public string KayitTarihi { get; set; }
        public Nullable<int> OdeyenFirma { get; set; }
        public Nullable<int> OdenecekFirma { get; set; }
        public string CariKodu { get; set; }
        public string Tutar { get; set; }
        public string Kur { get; set; }
        public string TalepTarihi { get; set; }
        public string OdemeTarihi { get; set; }
        public string Durum { get; set; }
        public Nullable<int> BankaID { get; set; }
        public string EvrakKime { get; set; }
        public string Evrakilgili { get; set; }
        public string Masraflar { get; set; }
        public string EvrakHesapNo { get; set; }
        public string EvrakKimeKodu { get; set; }
    }
}
