//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ContainerEvents
    {
        public int ID { get; set; }
        public string BLNO { get; set; }
        public string LINE { get; set; }
        public string CNTR_NO { get; set; }
        public string LOCATION { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> ACTUAL { get; set; }
        public string TYPE { get; set; }
        public string VESSELNAME { get; set; }
        public string VOYAGENR { get; set; }
        public Nullable<System.DateTime> LASTREQUESTDATE { get; set; }
    }
}
