//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Firmalar
    {
        public int id { get; set; }
        public Nullable<int> BagliFirmaID { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaAdiEn { get; set; }
        public string Adres { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string Postakodu { get; set; }
        public string Telno { get; set; }
        public string Faksno { get; set; }
        public string FirmaKodu { get; set; }
        public string SubeKodu { get; set; }
        public string EvrakTEPE { get; set; }
        public string EvrakLOGO { get; set; }
        public string BankaTR { get; set; }
        public string BankaENG { get; set; }
        public string BankaENG2 { get; set; }
        public string EvrakTEPEmuhasebe { get; set; }
        public Nullable<int> Aktif { get; set; }
        public string SubeEmail { get; set; }
        public string BankaTRyeni { get; set; }
        public Nullable<int> MuhasebeEntegrasyon { get; set; }
        public string VarsayilanDoviz { get; set; }
    }
}
