//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Quotes
    {
        public int ID { get; set; }
        public string TeklifNo { get; set; }
        public Nullable<int> RevizeNo { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> TeklifDurum { get; set; }
        public Nullable<int> Modul { get; set; }
        public Nullable<int> IthIhr { get; set; }
        public Nullable<int> Istipi { get; set; }
        public string FirmaAdi { get; set; }
        public Nullable<int> FirmaKodu { get; set; }
        public string IlgiliKisi { get; set; }
        public string IlgiliEmail { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string YuklemeYeri { get; set; }
        public string YuklemeLimani { get; set; }
        public string YuklemeLimaniKodu { get; set; }
        public string VarisLimani { get; set; }
        public string VarisLimaniKodu { get; set; }
        public string TeslimYeri { get; set; }
        public string IncoTerm { get; set; }
        public string PaymentTerms { get; set; }
        public string EkSartlar { get; set; }
        public Nullable<int> ToplamGoster { get; set; }
        public string KonsolideDoviz { get; set; }
        public string TeklifDili { get; set; }
        public string Red_Aciklama { get; set; }
        public string Red_Sebep { get; set; }
        public string Onaylayan { get; set; }
        public Nullable<System.DateTime> OnaylamaTarihi { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RezervasyonID { get; set; }
        public string RezervasyonNo { get; set; }
    }
}
