//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CntrTracking
    {
        public int TrackID { get; set; }
        public string KonteynerNo { get; set; }
        public string BLNo { get; set; }
        public string Nereden { get; set; }
        public string Nereye { get; set; }
        public string SonKonum { get; set; }
        public Nullable<System.DateTime> DolumTarihi { get; set; }
        public Nullable<System.DateTime> CutOff { get; set; }
        public string IlkYuklemeYeri { get; set; }
        public Nullable<System.DateTime> IlkYuklemeTarihi { get; set; }
        public string SonTeslimYeri { get; set; }
        public Nullable<System.DateTime> SonTeslimTarihi { get; set; }
        public Nullable<System.DateTime> BeklenenKalkisTarihi { get; set; }
        public Nullable<System.DateTime> BeklenenVarisTarihi { get; set; }
        public string KalkisLimani { get; set; }
        public string KalkisLimaniKod { get; set; }
        public Nullable<System.DateTime> KalkisTarihi { get; set; }
        public string KalkisGemisi { get; set; }
        public string KalkisGemisiSeferNo { get; set; }
        public Nullable<System.DateTime> Aktarma1VarisTarihi { get; set; }
        public string Aktarma1YuklemeLimani { get; set; }
        public string Aktarma1YuklemeLimaniKod { get; set; }
        public Nullable<System.DateTime> Aktarma1YuklemeTarihi { get; set; }
        public string Aktarma1YuklemeGemisi { get; set; }
        public string Aktarma1YuklemeGemisiSeferNo { get; set; }
        public string Aktarma2YuklemeLimani { get; set; }
        public string Aktarma2YuklemeLimaniKod { get; set; }
        public Nullable<System.DateTime> Aktarma2YuklemeTarihi { get; set; }
        public string Aktarma2YuklemeGemisi { get; set; }
        public string Aktarma2YuklemeGemisiSeferNo { get; set; }
        public string VarisLimani { get; set; }
        public string VarisLimaniKod { get; set; }
        public Nullable<System.DateTime> VarisTarihi { get; set; }
        public string VarisGemisi { get; set; }
        public string VarisGemisiSeferNo { get; set; }
        public string CntrGateOut { get; set; }
        public Nullable<System.DateTime> CntrGateOut_Tarihi { get; set; }
        public string EmptyReturn { get; set; }
        public Nullable<System.DateTime> EmptyReturn_Tarihi { get; set; }
        public Nullable<System.DateTime> LastRequestDate { get; set; }
        public Nullable<int> IgnoreData { get; set; }
    }
}
