//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOADTRACKING
    {
        public int id { get; set; }
        public string toplamkonteyner { get; set; }
        public string txtsiparisno { get; set; }
        public string txtgonderici { get; set; }
        public string txtalici { get; set; }
        public string txtmusteriadi { get; set; }
        public string txtnotify { get; set; }
        public string FirmaNo { get; set; }
        public string txtistipi { get; set; }
        public string txthblno { get; set; }
        public string txtkonteynerdolumtar { get; set; }
        public string txthat { get; set; }
        public string txtyuklemegemisi { get; set; }
        public string txtyuklemegemisiseferno { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtkalkistarihi { get; set; }
        public string txtvaristarihi { get; set; }
        public string txttahliyelimani { get; set; }
        public string txtmaladiyabanci { get; set; }
        public string txtyukdurum { get; set; }
        public string txtordinoteslimtarihi { get; set; }
        public string pozisyonno { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string toplambrutagirlik { get; set; }
        public string txtbrutagirlik { get; set; }
        public string txtsube { get; set; }
        public string txtacilistarihilong { get; set; }
        public string txtbeklenenvaristar { get; set; }
        public string cmbkonteynerboyu { get; set; }
        public string txthacim { get; set; }
        public string txtmblno { get; set; }
    }
}
