//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IsoTankStock
    {
        public int TankID { get; set; }
        public Nullable<int> PozisyonID { get; set; }
        public Nullable<int> YukID { get; set; }
        public string Sube { get; set; }
        public Nullable<bool> HANDRAIL_EQUIP { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public Nullable<int> BUILT_YEAR { get; set; }
        public Nullable<System.DateTime> NEXT_HYDROLIC_TEST { get; set; }
        public Nullable<System.DateTime> NEXT_AIR_TEST { get; set; }
        public string PozisyonNo { get; set; }
        public string TOwner { get; set; }
        public string ContainerNr { get; set; }
        public string YuklemeLimani { get; set; }
        public string YuklemeGemisi { get; set; }
        public string TahliyeLimani { get; set; }
        public string MalAdi { get; set; }
        public Nullable<System.DateTime> DolumTarihi { get; set; }
        public Nullable<System.DateTime> KalkisTarihi { get; set; }
        public Nullable<System.DateTime> TahliyeTarihi { get; set; }
        public Nullable<System.DateTime> AracYuklemeTarihi { get; set; }
        public string YuklemeYeri { get; set; }
        public Nullable<System.DateTime> AracBosaltmaTarihi { get; set; }
        public string BosaltmaYeri { get; set; }
        public Nullable<System.DateTime> DepoGiris { get; set; }
        public string Depo { get; set; }
        public Nullable<System.DateTime> DepoCikis { get; set; }
        public int DOLULUK { get; set; }
        public Nullable<long> All_ID { get; set; }
        public string DURUM { get; set; }
    }
}
