//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Araclar
    {
        public int ID { get; set; }
        public Nullable<int> SoforID { get; set; }
        public string PlakaNo { get; set; }
        public string AracCinsi { get; set; }
        public Nullable<int> ModelYili { get; set; }
        public Nullable<long> MevcutKilometre { get; set; }
        public Nullable<long> GelecekBakimKilometre { get; set; }
        public Nullable<System.DateTime> SonBakimTarihi { get; set; }
        public Nullable<System.DateTime> GelecekMuayeneTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
    }
}
