//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ShellView
    {
        public int ID { get; set; }
        public string Konu { get; set; }
        public string Duzenleyen { get; set; }
        public string Kontrol_Eden { get; set; }
        public string Kontrol_Frekansi { get; set; }
        public string Planlanan { get; set; }
        public string OCAK { get; set; }
        public string SUBAT { get; set; }
        public string MART { get; set; }
        public string NISAN { get; set; }
        public string MAYIS { get; set; }
        public string HAZIRAN { get; set; }
        public string TEMMUZ { get; set; }
        public string AGUSTOS { get; set; }
        public string EYLUL { get; set; }
        public string EKIM { get; set; }
        public string KASIM { get; set; }
        public string ARALIK { get; set; }
    }
}
