//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Individual_Goals
    {
        public int ID { get; set; }
        public Nullable<int> Performance_ID { get; set; }
        public string Targets { get; set; }
        public string Success_Criteria { get; set; }
        public Nullable<double> Target_Weight { get; set; }
        public Nullable<double> Success_Weight { get; set; }
        public Nullable<System.DateTime> Planned_Completion_Date { get; set; }
        public string Evaluation_Achieved { get; set; }
    }
}
