//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inform_Company
    {
        public int ID { get; set; }
        public Nullable<int> MODULE { get; set; }
        public Nullable<int> POZID { get; set; }
        public Nullable<int> LOADID { get; set; }
        public Nullable<int> DOCUMENT_TYPE { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public string RECIPIENTS { get; set; }
        public string BCC { get; set; }
        public Nullable<int> SEND_STATUS { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
    }
}
