//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Quote_Expenses
    {
        public int ID { get; set; }
        public Nullable<int> QUOTEID { get; set; }
        public string KalemAdi { get; set; }
        public string KalemAdiEn { get; set; }
        public Nullable<int> KalemKodu { get; set; }
        public string Hat { get; set; }
        public string HatKodu { get; set; }
        public Nullable<double> KdvOrani { get; set; }
        public Nullable<double> BirimTutar { get; set; }
        public string DovizKodu { get; set; }
        public Nullable<int> Kdv { get; set; }
        public string Dagitim { get; set; }
        public Nullable<int> KonteynerAdet { get; set; }
        public string KonteynerBoyu { get; set; }
        public string KonteynerSekli { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public string Aciklama { get; set; }
    }
}
