//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Menus
    {
        public int id { get; set; }
        public string MenuName { get; set; }
        public string Icon { get; set; }
        public Nullable<int> SectionID { get; set; }
    }
}
