//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HavaKonteyner
    {
        public int id { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string PozisyonNo { get; set; }
        public Nullable<int> PozisyonID { get; set; }
        public string YukNo { get; set; }
        public Nullable<int> YukID { get; set; }
        public string txtkonteynerno { get; set; }
        public string txtowner { get; set; }
        public string cmbkonteynerboyu { get; set; }
        public string cmbkonteynertipi { get; set; }
        public string txtmuhurno { get; set; }
        public string txtdara { get; set; }
        public string txtmaladi { get; set; }
        public Nullable<int> txtkolisayisi { get; set; }
        public string cmbpaketsekli { get; set; }
        public string cmbpaketseklien { get; set; }
        public string txthacim { get; set; }
        public string txtl { get; set; }
        public string txtw { get; set; }
        public string txth { get; set; }
        public string txtnetagirlik { get; set; }
        public string txtbrutagirlik { get; set; }
        public string cmbimoclass { get; set; }
        public string txtunno { get; set; }
        public string txtflashpoint { get; set; }
        public string txtsiparisno { get; set; }
        public string txtmarkabilgisi { get; set; }
        public string txtmaltanimi { get; set; }
        public string KonteynerBosTarihi { get; set; }
        public Nullable<int> DemurajGunSayisi { get; set; }
        public string DemurajUcreti { get; set; }
        public string DovizCinsi { get; set; }
        public Nullable<int> SerbestSure { get; set; }
        public string GemiTahliyeTarihi { get; set; }
        public string GemiYuklemeTarihi { get; set; }
        public string KonteynerDolumTarihi { get; set; }
        public string txthtkod { get; set; }
        public string txttoplamnavlun { get; set; }
        public Nullable<int> cktehlikeli { get; set; }
        public string CommodityItem { get; set; }
        public Nullable<double> Rate_Charge { get; set; }
        public string txtaciklama1 { get; set; }
        public string txtaciklama2 { get; set; }
        public string txtaciklama3 { get; set; }
        public string txtaciklama4 { get; set; }
        public string txtaciklama5 { get; set; }
        public string txtaciklama6 { get; set; }
        public string txtaciklama7 { get; set; }
        public Nullable<short> YildizSayisi { get; set; }
        public string Yorum { get; set; }
    }
}
