//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RezHavaPozisyonlar
    {
        public int id { get; set; }
        public string FirmaNo { get; set; }
        public string RezervasyonNo { get; set; }
        public Nullable<int> Rezerve { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string pozno { get; set; }
        public string pozisyonno { get; set; }
        public string txtistipi { get; set; }
        public string txtsube { get; set; }
        public string txtopgrup { get; set; }
        public string txtrezervasyontarihi { get; set; }
        public string txtopsiyontarihi { get; set; }
        public string txtopsiyonsaati { get; set; }
        public string txtacilistarihi { get; set; }
        public string txtacilistarihilong { get; set; }
        public string txtkapanistarihi { get; set; }
        public string txtyurtdisiacente { get; set; }
        public string txtmblno { get; set; }
        public string txtmbltarihi { get; set; }
        public string txthat { get; set; }
        public string txtkonteynerdolumtar { get; set; }
        public string txtbeklenenvaristar { get; set; }
        public string txtkalkistarihi { get; set; }
        public string txtvaristarihi { get; set; }
        public string txtyurtdisigemiacentesi { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtyuklemelimanitar { get; set; }
        public string txtyuklemegemisi { get; set; }
        public string txtyuklemegemisiseferno { get; set; }
        public string txtaktarmalimani { get; set; }
        public string txtaktarmalimanitar { get; set; }
        public string txtaktarmagemisi { get; set; }
        public string txtaktarmagemisiseferno { get; set; }
        public string txttahliyelimani { get; set; }
        public string txttahliyelimanitarihi { get; set; }
        public string txttahliyegemisi { get; set; }
        public string txttahliyegemisiseferno { get; set; }
        public string txtmanifestono { get; set; }
        public string txtmanifestotarihi { get; set; }
        public string txtgumrukluantrepo { get; set; }
        public string txtgumrukluantrepokod { get; set; }
        public string txtgumrukyeri { get; set; }
        public string txtgumrukyerikod { get; set; }
        public string txtnavluntarifesi { get; set; }
        public Nullable<int> txtnavluntardurum { get; set; }
        public string txtyurtdisiacentetar { get; set; }
        public Nullable<int> txtyurtdisiacentetardurum { get; set; }
        public string txtlimantarifesi { get; set; }
        public Nullable<int> txtlimantarifesidurum { get; set; }
        public string txticnakliyetarifesi { get; set; }
        public Nullable<int> txticnakliyetarifesidurum { get; set; }
        public string txtdemurajtarifesi { get; set; }
        public Nullable<int> txtdemurajtarifesidurum { get; set; }
        public Nullable<int> chkozetbeyantarifesidurum { get; set; }
        public string txtozetbeyantarifesi { get; set; }
        public string cmbincoterms { get; set; }
        public string toplambrutagirlik { get; set; }
        public string toplamnetagirlik { get; set; }
        public string toplamhacim { get; set; }
        public Nullable<int> toplamkolisayisi { get; set; }
        public string toplamkonteyner { get; set; }
        public string toplamnavlun { get; set; }
        public string txtyurtdisiacentekod { get; set; }
        public string txthatkod { get; set; }
        public string txtyuklemelimanikod { get; set; }
        public string txtaktarmalimanikod { get; set; }
        public string txttahliyelimanikod { get; set; }
        public string txtyurtdisigemiacentesikod { get; set; }
        public string txtyuklemegemisikod { get; set; }
        public string txtaktarmagemisikod { get; set; }
        public string txttahliyegemisikod { get; set; }
        public string txthavayoluantrepo { get; set; }
        public string txthavayoluantrepokod { get; set; }
        public string ekleyenkullanici { get; set; }
        public string eklemetarihi { get; set; }
        public string guncelleyenkullanici { get; set; }
        public string guncellemetarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string KullananKullanici { get; set; }
        public string KullanimBaslangic { get; set; }
        public string KullanimSon { get; set; }
        public Nullable<int> KullanimDurum { get; set; }
        public Nullable<int> KarZararDurum { get; set; }
        public string ToplamKarZararTL { get; set; }
        public string ToplamKarZarar { get; set; }
        public string FinansalGiderTL { get; set; }
        public string FinansalGider { get; set; }
        public string ToplamGelirlerTL { get; set; }
        public string ToplamGelirler { get; set; }
        public string ZararAciklama { get; set; }
        public string KarsiPozNo { get; set; }
        public string Rezervasyon_Mesajı { get; set; }
        public string Onaylayan { get; set; }
        public string Onay_Tarihi { get; set; }
        public string OnayaGonderen { get; set; }
        public string OnayaGonderenEmail { get; set; }
        public string OnayaGondermeZamani { get; set; }
        public Nullable<int> Rezervasyon_Durum { get; set; }
        public string Personel { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string txtekbilgi { get; set; }
        public string cmbmusteritahsilatsekli { get; set; }
        public string cmbvadegun { get; set; }
        public string txtBookingNumber { get; set; }
        public string txtcontractno { get; set; }
        public Nullable<int> TeklifID { get; set; }
    }
}
