//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TankStock
    {
        public int ID { get; set; }
        public string TANK_OWNER { get; set; }
        public string CNTR_NO { get; set; }
        public Nullable<bool> HANDRAIL_EQUIP { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public Nullable<int> BUILT_YEAR { get; set; }
        public Nullable<System.DateTime> NEXT_HYDROLIC_TEST { get; set; }
        public Nullable<System.DateTime> NEXT_AIR_TEST { get; set; }
        public Nullable<System.DateTime> INSPECTION_TEST { get; set; }
        public string LESSOR_COMPANY { get; set; }
        public string LESSOR_COMPANY_CODE { get; set; }
        public string LEASE_CONTRACT_NR { get; set; }
        public Nullable<System.DateTime> LEASE_CONTACT_DATE { get; set; }
        public Nullable<System.DateTime> LEASE_EXPIRE_DATE { get; set; }
        public string LEASE_DELIVERY_PLACE { get; set; }
        public string LEASE_REDELIVERY_PLACE { get; set; }
        public Nullable<System.DateTime> LEASE_ONDATE { get; set; }
        public Nullable<System.DateTime> LEASE_OFDATE { get; set; }
        public Nullable<double> DAILY_HIRE_RATE { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
    }
}
