//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Demuraj_Tarifeleri
    {
        public int id { get; set; }
        public string tarifeadi { get; set; }
        public string dovizcinsi { get; set; }
        public string liman { get; set; }
        public string hat { get; set; }
        public string tur { get; set; }
    }
}
