//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Messenger
    {
        public int id { get; set; }
        public Nullable<int> Kimden { get; set; }
        public Nullable<int> Kime { get; set; }
        public string Mesaj { get; set; }
        public string Tarih { get; set; }
        public Nullable<int> Okundu { get; set; }
    }
}
