//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CalisanToplamlari
    {
        public int ID { get; set; }
        public Nullable<int> FIRMA { get; set; }
        public Nullable<int> SUBE { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<int> OPERASYON { get; set; }
        public Nullable<int> SATIS { get; set; }
        public Nullable<int> DIGER { get; set; }
        public Nullable<int> YIL { get; set; }
    }
}
