//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Weekly_Visits
    {
        public int ID { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public string Staff { get; set; }
        public Nullable<int> ZIYARET { get; set; }
        public Nullable<int> YUKALIMI { get; set; }
    }
}
