//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MailGroups
    {
        public int id { get; set; }
        public string Sube1Operation { get; set; }
        public string Sube1RezervasyonOnay { get; set; }
        public string Sube1RezervasyonBilgilendirme { get; set; }
        public string Sube1HavaRezervasyonOnay { get; set; }
        public string Sube1HavaRezervasyonBilgilendirme { get; set; }
        public string OperationMail { get; set; }
        public string FinanceMail { get; set; }
        public string BudgetMail { get; set; }
        public string ManagementMail { get; set; }
        public string EveryBodyMail { get; set; }
        public string Sube1Mail { get; set; }
        public string Sube2Mail { get; set; }
        public string Sube3Mail { get; set; }
        public string Sube4Mail { get; set; }
        public string Sube5Mail { get; set; }
        public Nullable<int> SubeNo { get; set; }
        public string IsTipi { get; set; }
        public string UstYonetim1Kademe { get; set; }
    }
}
