//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tarifeler
    {
        public int id { get; set; }
        public Nullable<int> txtsube { get; set; }
        public string txttarifeadi { get; set; }
        public string cmbtarifetipi { get; set; }
        public string TarifeTuru { get; set; }
        public string txtfirmaadi { get; set; }
        public string txtfirmaadikod { get; set; }
        public Nullable<System.DateTime> txtbaslangictarihi { get; set; }
        public Nullable<System.DateTime> txtbitistarihi { get; set; }
        public string txtyuklemeyeri { get; set; }
        public string txtyuklemeyerikod { get; set; }
        public string txtyuklemelimani { get; set; }
        public string txtyuklemelimanikod { get; set; }
        public string txtvarislimani { get; set; }
        public string txtvarislimanikod { get; set; }
        public string txtnihaimevrit { get; set; }
        public string txtnihaimevritkod { get; set; }
        public string GuncelleyenKullanici { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string EkleyenKullanici { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
    }
}
