//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RezKaraKonteyner
    {
        public int id { get; set; }
        public Nullable<int> ithihr { get; set; }
        public string PozisyonNo { get; set; }
        public Nullable<int> PozisyonID { get; set; }
        public string YukNo { get; set; }
        public Nullable<int> YukID { get; set; }
        public string txtaractipi { get; set; }
        public string txtaractipikod { get; set; }
        public string txtcekiciplaka { get; set; }
        public string txtdorseplaka { get; set; }
        public string txtkonteynerno { get; set; }
        public string cmbkonteynerboyu { get; set; }
        public string cmbkonteynertipi { get; set; }
        public string txtdara { get; set; }
        public string txtmaladi { get; set; }
        public Nullable<int> txtkolisayisi { get; set; }
        public string cmbpaketsekli { get; set; }
        public string cmbpaketseklien { get; set; }
        public string txthacim { get; set; }
        public string txtl { get; set; }
        public string txtw { get; set; }
        public string txth { get; set; }
        public string txtnetagirlik { get; set; }
        public string txtbrutagirlik { get; set; }
        public string cmbimoclass { get; set; }
        public string txtunno { get; set; }
        public string txtflashpoint { get; set; }
        public string txtsiparisno { get; set; }
        public string txtmarkabilgisi { get; set; }
        public string txtmaltanimi { get; set; }
        public string txtnakliyefirmasi { get; set; }
        public string txtnakliyefirmasikod { get; set; }
        public string txtnakliyedeposu { get; set; }
        public string txtsurucuadisoyadi { get; set; }
        public string txtsurucugsm { get; set; }
        public string txtaracyuklemetarihi { get; set; }
        public string txtaracyuklemeyeri { get; set; }
        public string txtaracbosaltmatarihi { get; set; }
        public string txtaracbosaltmayeri { get; set; }
        public string txtowner { get; set; }
        public string txthtkod { get; set; }
        public string txtmuhurno { get; set; }
        public string txtflexitankno { get; set; }
    }
}
