//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RezervasyonKonteyner
    {
        public int id { get; set; }
        public Nullable<int> RezID { get; set; }
        public Nullable<int> Adet { get; set; }
        public string KonteynerBoyu { get; set; }
        public string KonteynerTipi { get; set; }
        public string txtmarkabilgisi { get; set; }
        public string txtsiparisno { get; set; }
        public string EkleyenKullanici { get; set; }
        public string EklemeTarihi { get; set; }
    }
}
