//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inttra_Transactions
    {
        public int ID { get; set; }
        public Nullable<int> POZID { get; set; }
        public Nullable<int> TRANSACTION_TYPE { get; set; }
        public Nullable<int> TRANSACTION_STATUS { get; set; }
        public string BOOKING_NR { get; set; }
        public string INTTRA_REF_NR { get; set; }
        public string FREIGHT_FORWARDER_REF { get; set; }
    }
}
