//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Nullable<System.DateTime> TarihDate { get; set; }
        public string orjinaltutar { get; set; }
        public int PYID { get; set; }
        public int Pozisyon { get; set; }
        public Nullable<int> Tur { get; set; }
    }
}
