//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceleGetir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalsByShipper
    {
        public int ID { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<double> BRUTAGIRLIK { get; set; }
        public Nullable<double> TOPLAMKOLI { get; set; }
        public string GONDERICI { get; set; }
        public string MUSTERIADI { get; set; }
        public string MUSTERIKODU { get; set; }
    }
}
